### ISSUE TITLE
NPM and JS SDK not working with angular

### ISSUE THREAD

**Issue by Kaoschuks** [ConnectyCube/connectycube-js-sdk-releases#104]
ERROR Error: Uncaught (in promise): ReferenceError: ConnectyCube is not defined
ReferenceError: ConnectyCube is not defined.

**Comment by Avia-Code** [comment]
Hi @Kaoschuks, you can see connectycube-web-sample in angular, which use JS SDC here: https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat-conf-angular
Please do the following to connect JS SDC to Angular project:
1. Simply install the package in a normal way:
     `npm install connectycube --save`
2.  Specify the path to connectycube.min.js in angular.json: 
     `"scripts": ["./node_modules/connectycube/dist/connectycube.min.js"]`
3.  Write this code, where you use `ConnectyCube` in your project `declare let ConnectyCube: any;`

**Comment by Kaoschuks** [comment]
Here are the errors I get now after following those steps you stated @Avia-Code......
<img width="1063" alt="Screenshot 2022-01-10 at 10 30 17" src="https://user-images.githubusercontent.com/15983722/148761191-3b271a8e-db9d-4790-9922-1a395b3a152d.png">

**Comment by Avia-Code** [comment]
It's possible you write `ConnectyCube` twice. You can try replace `ConnectyCube.ConnectyCube.createSession` to `ConnectyCube.createSession`.

**Comment by Kaoschuks** [comment]
Not working

**Comment by Kaoschuks** [comment]
Please check the repo https://github.com/Kaoschuks/ionic-videocalling

**Comment by Avia-Code** [comment]
So i checked your repo, you forgot initialize framework with your ConnectyCube application credentials `ConnectyCube.init(CREDENTIALS);`
I replaced your code in constructor to this:
```
constructor() {
    ConnectyCube.init(CREDENTIALS);
    ConnectyCube.createSession()
      .then((session) => {
        console.log(session);
      })
      .catch((error) => {
      });
  }
```
Anyway read the https://developers.connectycube.com/js/ carefully

**Comment by Kaoschuks** [comment]
thanks @Avia-Code works for web but not for Cordova or ionic capacitor

**Comment by Avia-Code** [comment]
ConnectyCube have repo for cordova, please create new issues to: https://github.com/ConnectyCube/connectycube-cordova-samples
