### ISSUE TITLE
CRA V5 support / use of node polyfills

### ISSUE THREAD

**Issue by Velua** [ConnectyCube/connectycube-js-sdk-releases#107]
It appears this library is relying on Node.js polyfills which don't come inbuilt in Creact react app version 5, this forces one to eject their app and mess around with webpack in attempt to support which is quite the expense. 

Is there intentions of updating this or creating a browser friendly version?

**Comment by DaveLomber** [comment]
@Velua there is already a browser friends version https://developers.connectycube.com/js/?id=browser

is there any issues with it?

**Comment by DaveLomber** [comment]
All the sample https://github.com/ConnectyCube/connectycube-web-samples were updated to newer versions with dependencies, let us know if you still face anything like this there
