### ISSUE TITLE
Remove chat history from Both Customer and driver Side 

### ISSUE THREAD

**Issue by GimmeForeDev1** [ConnectyCube/connectycube-js-sdk-releases#109]
Hello Team, 
In one of my React Native project i have implement connectCuby chat. 
Now, I'm facing some issues while I'm remove the chat history. the issue description is following, 

I want to remove complete history of single chat_room (Dialog_Id) with using ConnectyCube.chat.dialog.delete(dialogId).catch((error) => {}); function of connectCube. 
But in my case what happend these function is only clear the history from driver side of particular chat_room, but i want to complete remove all the history of **both side** which is Customer and driver side while pressing Complete order Button from Driver side application . 

Can you please help me or guild how to remove complete history of particular chat_room from Both side . 
Thank you in advance.

**Comment by DaveLomber** [comment]
To remove a dialog completely, set `force=1` parameter in the DELETE request. Only chat owner (creator) can do this.
