### ISSUE TITLE
Is It Possible To Create Admin User ?

### ISSUE THREAD

**Issue by jostney** [ConnectyCube/connectycube-js-sdk-releases#110]
Simply, i need a user who is able to update records (i have custom object called person)

Because, i setup user presence integration between connectycube and firebase admin.  So when a user goes offline(app closing or network disconnection) then firebase admin detects and receive the user's id, finally updates person object (like status = offline)

So at this point, i need a connectycube admin user for firebase admin to update records.

**Comment by DaveLomber** [comment]
@jostney you can do so already via permissions 

<img width="1247" alt="Screenshot 2022-10-02 at 17 39 30" src="https://user-images.githubusercontent.com/39332586/193459884-5229bff5-d6bc-4387-a03b-60304d7ca08b.png">

For your case, using Class level Permissions will be the easiest way to achieve the goal
