### ISSUE TITLE
Get the call logs

### ISSUE THREAD

**Issue by hatreact** [ConnectyCube/connectycube-js-sdk-releases#112]
I logged the session on accept listener and stop listener. 

**Accept Listener**

> In session object startCallTime have date and time.
> In session answerTimer have some number value.

 
**Stop Listener**

> In session object startCallTime have same time as above.
> In session answerTimer have always null value. 

So my question is can I get the time between a call or I can calculate the time if in **Stop Listener** we have different time for startCallTime and somehow push it to connecty cube dashboard. And then retrieve the logs later.

**Comment by DaveLomber** [comment]
You can calculate time between Call/Accept and Stop

Then you can store this data in a `Custom` module

<img width="1500" alt="Screenshot 2023-02-08 at 14 15 10" src="https://user-images.githubusercontent.com/39332586/217527294-d5b09e0e-fdba-4995-815b-de27a5434299.png">

The API is available under `ConnectyCube.data.create(className, fields)`, `ConnectyCube.data.list(className, filters)` etc

**Comment by hatreact** [comment]
Only possible if i get different time when accepting and stopping the call. I get the same startCallTime for both cases. Sometimes when accepting the call, startCallTime is zero.

**Comment by hatreact** [comment]
I didn't get proper `startCallTime` in both listener(Accept, Stop).
So When receiver accepted the call. I made my own timer. When call is accepted then i get the currently available time and when user stop the call i then get the available time at that moment. I then subtract to get the time of the call.
