### ISSUE TITLE
TURN servers are not currently connecting 

### ISSUE THREAD

**Issue by owinter86** [ConnectyCube/connectycube-js-sdk-releases#113]
We have some users reporting black screens when trying to make calls, and I have confirmed that calls work fine if made with both devices on the local network, but as soon as single device switches to mobile data, or we change the configuration to `alwaysRelayCalls: true` then the video call connection is never made and the `onIceConnectionStateCallback` is stuck on `connecting`.

We have switched out the connectycube IceServers to metered.ca ones, and the problem is solved. So I believe there is an issue with the current connectycube turn servers.

**Comment by TatankaConCube** [comment]
could you please try our stun/turn servers now? please close the ticket if your issue was resolved

**Comment by owinter86** [comment]
Looks like the issue is now resolved, thanks for your prompt response.
