### ISSUE TITLE
Redux is not updating, hence can't video call or receive call

### ISSUE THREAD

**Issue by hatreact** [ConnectyCube/connectycube-js-sdk-releases#115]
Versions:
```
"react-native-connectycube": "^3.22.3",
"react-native-incall-manager": "^4.0.1",
"react-native-invoke-app": "^1.0.6",
"react-native-callkeep": "^4.3.3",
"react-native-notifications": "^4.3.1",
```

Issue:
- Caller starts the AudioCall.
- Actions are being dispatched and states are updating while starting the call.
- Video Screen appears.
- Redux is not updating and not showing the updated states in VideoScreen.
- Receiver can hear the incoming ringtone.
- IncomingCallScreen doesn't appear on receiver's side.
- Incase of VideoCall, same steps happen but camera doesn't show

Caller's logs:

<img width="1672" alt="Screenshot 2023-11-13 at 11 44 35 PM" src="https://github.com/ConnectyCube/connectycube-js-sdk-releases/assets/124583031/9ab90620-d955-423e-b086-25e1824f1eb3">
<img width="1675" alt="Screenshot 2023-11-13 at 11 45 01 PM" src="https://github.com/ConnectyCube/connectycube-js-sdk-releases/assets/124583031/d482fe44-94e2-4b62-8c05-306c5e957485">

Receiver's logs:

<img width="1671" alt="Screenshot 2023-11-13 at 11 50 16 PM" src="https://github.com/ConnectyCube/connectycube-js-sdk-releases/assets/124583031/28bfa20a-15f7-4a48-ac47-9f7868b79cf1">

As you can see in receiver's logs, right above [VIDEO-SCREEN] log at the end of the line, you'll see true value. This is isIncoming value. In receiver's logs, [SET_CALL_SESSION] log run when _onCallListener function run on receiver's side. And in [VIDEO-SCREEN] log the session is null, which shouldn't be.

Why ActiveCall reducer behaving strangely despite actions being dispatched correctly?

**Comment by hatreact** [comment]
```
 const startCall = async (callType = "video") => {
    CallService.getStore(store);
    if (user.UserSetting.ccuid == null) {
      showToast("User does not have a valid connectycube id");
      return;
    }

    const selectedOpponentsIds = [user.UserSetting.ccuid];

    const callSession = await CallService.startCall(
      selectedOpponentsIds,
      callType == "video"
        ? ConnectyCube.videochat.CallType.VIDEO
        : ConnectyCube.videochat.CallType.AUDIO,
      { token, callType, userId: user.id }
    );

    const pushParams = {
      message: `Incoming call from ${user.firstName}`,
      ios_voip: 1,
      handle: user.firstName,
      initiatorId: callSession.initiatorID,
      opponentsIds: selectedOpponentsIds.join(","),
      uuid: callSession.ID,
      callType,
    };

    PushNotificationsService.sendPushNotification(
      selectedOpponentsIds,
      pushParams
    );

    navigation.navigate("VideoScreen", {
      initiatorName: user,
    });
  };
```
`CallService.startCall` ran and streams is passed to action `ADD_OR_UPDATE_STREAMS`. You can see in Caller's log, 2nd image right above `ADD_OR_UPDATE_STREAMS[0]`. This stream is being accessed in `VideoScreen` by using this selector

`const streams = useSelector(store => store.ActiveCall.streams);`

Even though startCall is running successfully without any error, when user navigates to `VideoScreen` right after `startCall`. 

`const callSession = useSelector(store => store.ActiveCall.session);`
`callSession` is still null. So I passed `callSession` in `VideoScreen` to confirm if session coming through. That's why it was showing warning for Non-serializable values.

`_onCallListener` ran and session is dispatched.
`_onRemoteStreamListener` is not triggering at all.

**Comment by ccvlad** [comment]
Can you display the localStream (a media stream from a device's camera)? Check [this](https://developers.connectycube.com/reactnative/videocalling?id=access-local-media-stream).

> `_onCallListener` ran and session is dispatched.
`_onRemoteStreamListener` is not triggering at all.

Both users should get a remote stream in `onRemoteStreamListener` after the receiver does `session. accept(extension)` inside the `onCallListener = (session, extension) => {...}`. Also, check this [guide](https://developers.connectycube.com/reactnative/videocalling?id=accept-a-call).

======================================

Your steps to set a call between users should look like this:
- a caller [creates a call session](https://developers.connectycube.com/reactnative/videocalling?id=create-video-session);
- the caller [initiates the call](https://developers.connectycube.com/reactnative/videocalling?id=initiate-a-call);
- the callee [gets and accepts the call](https://developers.connectycube.com/reactnative/videocalling?id=accept-a-call);
- then callee and caller get remote streams from each other in the `ConnectyCube.videochat.onRemoteStreamListener = function (session, userID, remoteStream) { /*use the remoteStream*/ }`
- also, the callee makes and [attaches a local stream](https://developers.connectycube.com/reactnative/videocalling?id=attach-local-media-stream) if needed.

Make sure you have remote streams, then you can dispatch them to Redux to be able to use them from Redux state on any screen. You can test Redux with a local stream first because it is created locally.

**Comment by hatreact** [comment]
No I'm not able to see media stream from device's camera.

**With my code**

`static MEDIA_OPTIONS_AUDIO = { audio: true };`

```
 async startCall(usersIds, callType, options = {}) {
    const session = ConnectyCube.videochat.createNewSession(
      usersIds,
      callType,
      options
    );
    store.dispatch(setCallSession(session));

    await this.setMediaDevices();

    // create local stream
    // I write local stream logic like this for readability
    
    const stream = await this.callSession.getUserMedia(
      callType == 2
        ? CallService.MEDIA_OPTIONS_AUDIO
        : CallService.MEDIA_OPTIONS
    );
    console.log("[START-STREAM][0]", stream);

    // store streams
    const streams = [{ userId: LOCAL_STREAM_USER_ID, stream: stream }];
    for (let uId of usersIds) {
      streams.push({ userId: parseInt(uId), stream: null });
    }
    console.log("streams", streams);
    store.dispatch(addOrUpdateStreams(streams));

    this.callSession.call({ options });

    const userName = `${this.currentUser.firstName} ${this.currentUser.lastName}`;
    const receivedNames = await getCallRecipientString(usersIds);

    // report to CallKit (iOS only)
    this.reportStartCall(
      this.callSession.ID,
      userName,
      receivedNames,
      "generic",
      callType === "video"
    );

    this.playSound("outgoing");

    return session;
  }
```

<img width="1674" alt="Screenshot 2023-11-15 at 6 23 57 PM" src="https://github.com/ConnectyCube/connectycube-js-sdk-releases/assets/124583031/6cbbdf51-14b2-4cb5-a0bd-8c29de9ec487">

**With  connectycube sample code**

```
async startCall(usersIds, callType, options = {}) {
    const session = ConnectyCube.videochat.createNewSession(
      usersIds,
      callType,
      options
    );
    store.dispatch(setCallSession(session));

    await this.setMediaDevices();

     // create local stream
     const mediaOptions = {...CallService.MEDIA_OPTIONS};
     if (callType === ConnectyCube.videochat.CallType.AUDIO) {
       mediaOptions.video = false;
     }
     const stream = await this.callSession.getUserMedia(mediaOptions);
    console.log("[START-STREAM]", stream);

    // store streams
    const streams = [{ userId: LOCAL_STREAM_USER_ID, stream: stream }];
    for (let uId of usersIds) {
      streams.push({ userId: parseInt(uId), stream: null });
    }
    console.log("streams", streams);
    store.dispatch(addOrUpdateStreams(streams));

    this.callSession.call({ options });

    const userName = `${this.currentUser.firstName} ${this.currentUser.lastName}`;
    const receivedNames = await getCallRecipientString(usersIds);

    // report to CallKit (iOS only)
    this.reportStartCall(
      this.callSession.ID,
      userName,
      receivedNames,
      "generic",
      callType === "video"
    );

    this.playSound("outgoing");

    return session;
  }
```

<img width="1673" alt="Screenshot 2023-11-15 at 6 18 54 PM" src="https://github.com/ConnectyCube/connectycube-js-sdk-releases/assets/124583031/ee3092e4-f0d7-48a0-92f5-7342df803f97">


And **localStream** is shown in `<VideoGrid streams={streams} />` in **VideoScreen**.

I tried to follow documentation and compare code with [connectycube-reactnative-sdk](https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat) multiple times. And there is no step I have missed. 

- ConnectyCube inialized.
- Session starts
- CallService.init(); pushNotificationService.init(); Both these initialize after session starts successfully.
- I do get UDID for channels APNS, APNS VOIP and FCM and device are subscribe to PushNotification. I can see them in Push Notifications Queue on dashboard.
- `_onCallListener` runs and nothing happens afterwards.

My guess is it could be due to non-serialized values which could be **session** or **streams** being passed in redux. Maybe non-serialized values could be causing this unexpected behaviour. Do you think that it could cause serious problems?

**Comment by hatreact** [comment]
Sorry, previous logs were from audio call. I have tested on emulators/simulators and real devices.

Testing on following Devices. I get same behaviour.
iPhone XS MAX ios 15
OnePluse 6t android 11
Galaxy A52 android 13

![Uploading Screenshot 2023-11-20 at 3.27.16 PM.png…]()

I added log in `_createAndStoreSession` inside cubeWebRTCClient.js
![Uploading Screenshot 2023-11-20 at 4.38.12 PM.png…]()

**Comment by ccvlad** [comment]
> I added log in _createAndStoreSession inside cubeWebRTCClient.js

You've gotten the log of the new session, it’s obvious that it’s empty.

From previous logs I see that you have a correct localStream and sent it.
Check this call on a receiver side and accept the call session. You should get this stream as remote for the receiver (into the onRemoteStreamListener)

**Comment by hatreact** [comment]
<img width="1680" alt="Screenshot 2023-12-04 at 1 03 42 PM" src="https://github.com/ConnectyCube/connectycube-js-sdk-releases/assets/124583031/ce8549b7-a300-4b92-b68c-c16e78b4b2b4">


In `_onCallListener`, value for `isIcoming` is passed as true. But still it's not invoking `IncomingCallScreen`. When I log `isIcoming` value it is false which is very strange behaviour.

```
  async _onCallListener(session, extension) {
    this.token = extension.options.token;
    this.otherUserId = extension.options.userId;

    // if already on a call
    if (this.callSession && !this.isDummySession) {
      console.log("[CallService][_onCallListener] reject, already_on_call");
      this.rejectCall(session, { already_on_call: true });
      return;
    }

    this.playSound("incoming");

    console.log("[CallService][_onCallListener]", {
      isEarlyAccepted: this.isEarlyAccepted,
      isAccepted: this.isAccepted,
    });

    if (this.isEarlyAccepted && !this.isAccepted) {
      setTimeout(() => {
        // wait until redux updated the data
        this.acceptCall();
      });
    }

    console.log("[_onCallListener][Session]", session);

    store.dispatch(setCallSession(session, true));
  }
```

**Comment by hatreact** [comment]
Yeah I tried to integrate sample code as well but facing the same issue.

I created a repo with produceable behavior. It has the sample sdk code.
`https://github.com/hatreact/RAApp.git`

**Comment by DaveLomber** [comment]
@ccvlad could you follow up?

**Comment by ccvlad** [comment]
Hey, @hatreact !

I've used your project (RAApp) to find the issue and prepared diff file with fixes - [fix_redux_configurations.diff.zip](https://github.com/ConnectyCube/connectycube-js-sdk-releases/files/14144102/fix_redux_configurations.diff.zip)
I think you can apply this file by the command `git apply < path/to/fix_redux_configurations.diff` from the root of your project.

You made a lot of mistakes in setting up the redux lib, so I advise you to understand the redux documentation.

I haven't fixed other issues you might encounter later because you should figure it out for yourself.
