### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#12]
**Environment**
Safari 13.0.5
MacOS Catalina 10.15.3
Connectycube Javascript version: 1.8.1
VueJS

**Issue**
1. In comming call start
2. the user allow access to media devices (just in the 1st time)
3. error: `Attempted to assign to readonly property`

This how my accepCall method looks like

```
acceptCall() {
      const mediaParams = {
        video: this.isVideoCall,
        audio: true,
        elementId: "videoSender"
      };

      this.call.session.getUserMedia(mediaParams, error => {
        if (error) {
          // alert here
          return;
        }

        this.call.session.accept({});
        this.onAcceptCallListener();
      });
    },
```

Could you help me with that?

![image](https://user-images.githubusercontent.com/4874090/76677098-f6965f00-658f-11ea-835d-9166d5f1e7b2.png)

**Comment by DaveLomber** [comment]
Hi @masmerino13 
could you please provide an exact line where it crashes in ConnectyCube SDK
this will help us to identify the issue

**Comment by masmerino13** [comment]
Hi @DaveLomber ,
Let me try to detect which line, but basically be function below return the error that i'm talking about

```
this.call.session.getUserMedia(mediaParams, error => {
        if (error) {
          // alert here
          return;
        }

        this.call.session.accept({});
        this.onAcceptCallListener();
      });
```

**Comment by masmerino13** [comment]
Chrome and Firefox works well

**Comment by masmerino13** [comment]
Hope this help, thank you so much

![image](https://user-images.githubusercontent.com/4874090/76679758-8811cb00-65a8-11ea-85b6-6234e5a89805.png)

**Comment by masmerino13** [comment]
also my platform is online we are planning to publish this ASAP, any help is welcome.

**Comment by DaveLomber** [comment]
Thanks for the log, 
it seems something wrong is happening with Strophe lib we used for XMPP. 

We will check it ASAP and let you know

meanwhile, if this can help faster, recently we released SDK 2.0 and then 2.1 where we unified the Chat connection logic and got rid of the Strophe lib completely. 
The SDK itself is not fully compatible with 1.x series cause we moved away of callbacks and replaced all the API with promises,
just an alternative option https://connectycube.com/2020/01/24/announcing-2nd-generation-of-sdks-for-developing-chat-and-video-chat-apps-for-javascript-cordova-node-react-native-and-nativescript-apps/

and here is also a new Video Chat code sample based on SDK 2.0 https://developers.connectycube.com/js/code-samples?id=video-chat-code-sample

**Comment by masmerino13** [comment]
Thank you @DaveLomber , the new version looks good, we are going to plan a refactor there, BUT if is posible to have a quick fix with the current version will be great.

Any help is welcome.

Thanks!

**Comment by Kachanov-dev** [comment]
Hi @masmerino13.
New version of SDK 1.8.2 is ready. Has been fixed bug "attempted to assign to readonly property"  for Safari.

**Comment by masmerino13** [comment]
That sounds amazing!!!

Thank you @Kachanov-dev, that's great news, we have released our platform last weekend and we are scared about that.

Thank you so much.

**Comment by masmerino13** [comment]
Guys, thank you for the new release, I'm testing it and now i'm able to do the call.

BUT ;( now I only hear a BIP/BOP loop, it's happen only in Safari and for video calls instead of the camera of my Mac I see something else.

Please see the screenshots below.

![bip](https://user-images.githubusercontent.com/4874090/77020777-78003f80-694a-11ea-842e-8e86df6b56bc.png)
![bop](https://user-images.githubusercontent.com/4874090/77020778-79ca0300-694a-11ea-924e-2f9170223da9.png)

cc: @Kachanov-dev @DaveLomber

**Comment by Kachanov-dev** [comment]
Hi @masmerino13.
It's not a problem.
Safari doesn't allow to share the camera between two browsers (Safari). 
It works well if Safari run on two different devices

**Comment by masmerino13** [comment]
This is not my case, the bip/bop camera is the Mac that yo can see in the second picture, the second device is from my computer Ubuntu Linux.

**Comment by DaveLomber** [comment]
@masmerino13 apologize, seems I did not get your case fully 

could you please describe in details/steps, to make it more clear for us

Thanks !

**Comment by masmerino13** [comment]
np @DaveLomber , I really appreciate your help,

I did the upgrade to `SDK 1.8.2` and now I'm able to do the call, but having this issue that I have mentioned above.

No errors in the console, just that weird behavior ;(

Now with this upgrade, should I do any change in the `getUserMedia` statement?
Thank you so much!

**Comment by DaveLomber** [comment]
@masmerino13 right
could you please describe in more details this issue https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/12#issuecomment-600934569

1) what machines you use
2) browsers
3) who call whom 
4) what all parties then face

**Comment by masmerino13** [comment]
M1 = MacBook pro, Catalina 10.15.3, Safari 13.0.5, MacOS
M2 = Ubuntu 18, Chrome 79.0.3945.117 (Build oficial) (64 bits)

who call whom: Happen in both cases when M1 calls to M2 and when M2 calls to M1
what all parties then face: M1 can see (for vide calls) and hear to M2, but M2 can't see/hear to M1, just the bip/bop as the screenshots above

cc: @DaveLomber 

Thanks,

**Comment by ccvlad** [comment]
Hi, @masmerino13

Go to Safari Develop > WebRTC > (Uncheck) Use Mock Capture Devices

<img width="1068" alt="Screenshot 2020-03-19 at 18 45 06" src="https://user-images.githubusercontent.com/43810932/77092211-3c30ad00-6a12-11ea-8888-c7af0f5af4d0.png">

**Comment by DaveLomber** [comment]
@ccvlad  is it for which case?
please provide more detailed info what it supposed to resolve

**Comment by ccvlad** [comment]
> @ccvlad is it for which case?
> please provide more detailed info what it supposed to resolve

Disable of the "Use Mock Capture Devices" option will switch the "bip/bop" mode to the camera mode.

**Comment by masmerino13** [comment]
Thanks @ccvlad, let me try!

**Comment by masmerino13** [comment]
Hey guys,

Thanks a lot, works like a charm, i'm not sure when/how I enabled that option, thank you so much @ccvlad @DaveLomber @Kachanov-dev 

Sorry for the delay, i'm running on a lot of stuff those days.
