### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by sapkotamadhusudan** [ConnectyCube/connectycube-js-sdk-releases#13]
Can you please add the typescript support for react-native sdk

**Comment by ccvlad** [comment]
Hi, @sapkotamadhusudan 
We will add types for our SDK after few weeks.
You are able to use it without types in your  TS project.

**Comment by sapkotamadhusudan** [comment]
@ccvlad Thank you for your support :) .

**Comment by DaveLomber** [comment]
The new SDK 4.0 has been released with FULL TS support 
https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/4.0.0
