### ISSUE TITLE
the simplest node.js server wont work

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-js-sdk-releases#14]
get error -> error initialisingTypeError: Cannot read property 'CallType' of null

code-->

const http = require('http');
var ccube = require('connectycube');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');

// let urlParams = getParams(window.location.href);
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);

  const CONNECTYCUBE_APPLICATION_ID = xxxx;
  const CONNECTYCUBE_AUTHORIZATION_KEY = xxxxx
  const CONNECTYCUBE_AUTHORIZATION_SECRET = xxxxx
  
  
  const CONNECTYCUBE_CREDENTIALS = {
      appId: CONNECTYCUBE_APPLICATION_ID,
      authKey: CONNECTYCUBE_AUTHORIZATION_KEY,
      authSecret: CONNECTYCUBE_AUTHORIZATION_SECRET
    };
  
  ccube.init(CONNECTYCUBE_CREDENTIALS);

  let userCredentials = {
    userId: xxxxx,
   password: xxxx
  };
  

  ccube.chat
   .connect(userCredentials)
   .then(() => { 
  
  
    const calleesIds = [1197559]; // User's ids
    const _sessionType = ccube.videochat.CallType.VIDEO; // AUDIO is also possible
    const additionalOptions = {};
    const _session = ccube.videochat.createNewSession(calleesIds, _sessionType, additionalOptions);
   
  
    res.end('Hello World' + _session);
  
  })
  .catch(error => {console.log('error initialising' + error);});
  
});

**Comment by ccvlad** [comment]
The node.js doesn't support calls. It haven't API to get user media

**Comment by krisbaum74** [comment]
thanks for your reply.

I am just wanting to use node.js so that i can hide my api keys and secret - obviously client side javascript exposes these, can you suggest another way to implement?

thanks

**Comment by ccvlad** [comment]
You can create you ConnectyCube's session and authorize user in node.js server and send a session's token to [init](https://developers.connectycube.com/js/?id=initialize) SDK by the session's token, then connect to chat using the token as password.

```javascript
ConnectyCube.init({appId: "...", token: sessionToken}, config);
```

**Comment by krisbaum74** [comment]
great, thanks i will do that.

**Comment by krisbaum74** [comment]
can you please expand a  bit on the process here? it is not clear what order to do things. your react example does an init before anything. are you saying do a .init in node.js and pass the session info?

**Comment by ccvlad** [comment]
You can create a small node.js service that can create ConnectyCube session and login your user.

1. From client side you have to post some data that will be used to define your user (user.login/user.id/user.email and user.password)
2. On server side you will get this data, define user and send back response:
```javascript
const ConnectyCube = require("connectycube");

const CREDENTIALS = {
  appId: 888,
  authKey: "hhf87hfushuiwef",
  authSecret: "jjsdf898hfsdfk"
};

const CONFIG = {
  debug: { mode: 1 }
};

ConnectyCube.init(CREDENTIALS, CONFIG);

// get POST request this user's data and create session with user:
const userCredentials = {
    login: 'some_user', // or 
    password: 'awesome_pass'
};

ConnectyCube.createSession(userCredentials)
    .then(session => {
        // save session.token and response to the client side.
    })
    .catch(error => { /* error */ });
``` 
*** [session](https://developers.connectycube.com/server/auth?id=response-1).token

3. Then initialise ConnectyCube SDK on client side:
```javascript
// obtain sessionToken from node.js server and do init (just **appId** and **token** is needed)
ConnectyCube.init({appId: 888, token: sessionToken}, connectyCubeConfig);

// SDK was initialised and you can do REST API calls to the ConnectyCube server.

// Connect to chat using sessionToken:
ConnectyCube.chat.connect({
    userId: 909809,
    password: sessionToken
}).then(() => {
    // connected
});
```
4. You are able to use [videochat's methods](https://developers.connectycube.com/js/videocalling?id=create-video-session)

**Comment by krisbaum74** [comment]
thanks actually i had done almost exact the same but discovered it would not work in Firebase functions for some reason, it falls over at the createSession. init works fine.

so now i have it working on a local node server but ideally wanted it on Firebase as a cloud function.

**Comment by ccvlad** [comment]
Try to create new [empty session](https://developers.connectycube.com/js/authentication-and-users?id=create-session-token). Then get Firebase access token and [login via Firebase](https://developers.connectycube.com/js/authentication-and-users?id=authentication-via-phone-number)

**Comment by ccvlad** [comment]
Closed due inactivity, please re-open if the issue is still persists.
