### ISSUE TITLE
switching video camera

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-js-sdk-releases#16]
i understand you can get a list of video devices, but how do you tell which is the current video device?

also are there any plans to have a broadcast feature? where one person's camera can feed as many other users as desired?

**Comment by krisbaum74** [comment]
any update on this?

**Comment by DaveLomber** [comment]
@krisbaum74 please find a link to Switch Camera API 
https://developers.connectycube.com/js/videocalling?id=switch-video-cameras 

As for the broadcast feature - we are on our way to make a first beta release soon.
As for now - it will support a use case 'teacher/students' - up to 100 subscribers.
Let us know if you are looking for something like this

**Comment by krisbaum74** [comment]
This doesnt tell you what the current device is, how can i tell what that is?

**Comment by krisbaum74** [comment]
"As for now - it will support a use case 'teacher/students' - up to 100 subscribers.
Let us know if you are looking for something like this"

yes please, where do i get the API info?

**Comment by DaveLomber** [comment]
There are 2 solutions, mainly:

1) You can use the following to initially get a specific device id, so you can store the ref locally to it: 

```
let availableVideoDevices;

ConnectyCube.videochat
    .getMediaDevices('videoinput')
    .then(devices => {
       availableVideoDevices = devices
    })
    .catch(error => {});
```

```
let activeDeviceId = availableVideoDevices[0].deviceId;

const mediaParams = {
    audio: true,
    video: { deviceId: { exact: activeDeviceId } }
};

session
    .getUserMedia(mediaParams)
    .then(localStream => {})
    .catch(error => {});
```

so in this case, a `activeDeviceId ` variable will hold an active device id

2) use the previous approach, but extract an active device id from an obtained local stream:

```
let activeDeviceId;

const mediaParams = {
    audio: true,
    video: true,
    options: {
        muted: true,
        mirror: true
    }
};

session
    .getUserMedia(mediaParams)
    .then(localStream => {
        localStream.forEach(track => {
           if (track.kind === 'video') {
              activeDeviceId = track.getSettings().deviceId;
           }
       });
    })
    .catch(error => {});
```

But, keep in mind, a `track.getSettings()` is not available everywhere, so need to check before using it

**Comment by krisbaum74** [comment]
Ok so it's always [0] in the list of available devices. Might be good to
put that in the docs.
