### ISSUE TITLE
password change not changing password - JS (React Native)

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-js-sdk-releases#19]
const updatedUserProfile = {
          login: userCredentials.login,
          full_name: fullName,
          password: password,
          old_password: oldPassword
          };

      }

  // JS SDK v2
  ConnectyCube.users
      .update(updatedUserProfile)
      .then(user => {
          console.log('updated user!!');
          console.log(user)
            })
      .catch(error => {});

console gets updated user, and the full name can be updated but the password doesnt change even though oldpassword is same as the one used to login.

**Comment by ccvlad** [comment]
Hi, @krisbaum74 
1. Did you try to login with new password after updating?
2. What the log (response from server)?

*note: you won't get new password in response cause security.

**Comment by krisbaum74** [comment]
Yes and it's still the old password. It doesn't change the password.

Server log from ConnectyCube?
No error is thrown

Kris

**Comment by ccvlad** [comment]
I will test the code and let you know

**Comment by ccvlad** [comment]
I've tested and code works as expected (I was able to change password and login with new).

1. Are you trying to change password for current user?
2. Please provide your logs (from _ConnectyCube.createSession()_ to _ConnectyCube.users.update()_)

**Comment by ccvlad** [comment]
Closed due inactivity, please re-open if the issue is still persists.
