### ISSUE TITLE
attachment sending docs confusing

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-js-sdk-releases#22]
```
const prepareMessageWithAttachmentAndSend = file => {
  const message = {
    type: dialog.type === 3 ? "chat" : "groupchat",
    body: "attachment",
    extension: {
      save_to_history: 1,
      dialog_id: dialog._id,
      attachments: [{ uid: result.uid, type: "photo" }]
    }
  };

  // send the message
  // ...
```

this the doc. are you saying with the //send the message that a sendmessage should be envoked or does connectycube already send a message with  -->>

```
// JS SDK v2
ConnectyCube.storage
  .createAndUpload(fileParams)
  .then(prepareMessageWithAttachmentAndSend)
  .catch(error => {});
```

**Comment by krisbaum74** [comment]
actually, can someone please update this example to have a full working one?

**Comment by DaveLomber** [comment]
@krisbaum74 you are right - 'send the message' means you should call a send message API like here https://developers.connectycube.com/js/messaging?id=sendreceive-chat-messages

We will update the guide to make it easier 

Thanks for reporting!

**Comment by DaveLomber** [comment]
The guide is updated

https://developers.connectycube.com/js/messaging?id=attachments-photo-video

Thank you !
