### ISSUE TITLE
Is there a user authentication with a pre generated user session token method?

### ISSUE THREAD

**Issue by Mike-Van** [ConnectyCube/connectycube-js-sdk-releases#23]
Hi. I'm very interested in your js sdk, and is thinking of integrating it into my react js and react native project, with serverless framework on backend. The thing is im looking for a custom auth function for nodejs that can log my user in and return a login token back to frontend. So that means i'd not log in my user directly on front end. i'd send my user `login` and `password` to my own server, where it'd login and return a token to frontend so the user can login wit just that token. Is there any function for that? cos i cant seem to find reference to it in the docs.

**Comment by Mike-Van** [comment]
Essentially, i need the login to go thru my backend to verify with my own users db among other matter, n only return the token back to frontend

**Comment by DaveLomber** [comment]
Hi @Mike-Van 

I believe you are looking for this https://developers.connectycube.com/js/?id=initialize-with-existing-token

**Comment by ccvlad** [comment]
Hi @Mike-Van 
SDK have ability to login via sessionToken that user can get from nodejs.
Here the guide - https://developers.connectycube.com/js/?id=initialize-with-existing-token

It meens that you will do `ConnectyCube.init()` with just `appId` and `sessionToken` and will setup session token for features API calls. Then you are also able to do `ConnectyCube.chat.connect({userId: user.id, password: sessionToken})`

**Comment by DaveLomber** [comment]
And here is a REST API doc for create session token  https://developers.connectycube.com/server/auth?id=create-session-with-user-authorization

**Comment by stephanoparaskeva** [comment]
What about using Refresh Tokens.

I use this self-hosted solution in my app and I cant figure out how to connect it with ConnectyCube
https://supertokens.io/docs/pro/getting-started/installation
