### ISSUE TITLE
VOIP Push Notification Issue

### ISSUE THREAD

**Issue by Unixon-solutions** [ConnectyCube/connectycube-js-sdk-releases#24]
_No recipients. At least one user should be subscribed for 'apnsvoip' (through SDK or REST API)_

I am getting above message when send notification to voip channel.

In app I have subscribed to "apns_voip" channel.

I think there is some mismatch in channel name.

Please fix this and let me know If there any changes required

Thanks.

**Comment by DaveLomber** [comment]
@Unixon-solutions please provide 2 code snippets: 

- how you subscribe a user for VOIP
- how you send a VOIP push

thanks

**Comment by Unixon-solutions** [comment]
passing `notification_channels: "apns_voip"` in `ConnectyCube.pushnotifications.subscriptions.create`

and sending notification from CC admin panel

**Comment by DaveLomber** [comment]
@Unixon-solutions just to make sure - the environment in both cases are production(live)?

I see it's live for Admin panel 

Is it also a production one for   `ConnectyCube.pushnotifications.subscriptions.create` ?

**Comment by Unixon-solutions** [comment]
I am using development build.

when I select Testing it shown as below screenshot. but didn't get any notification.
![Screenshot 2020-05-12 at 9 32 04 PM](https://user-images.githubusercontent.com/47319424/81717386-1cf54f80-9498-11ea-88d4-3585867599f2.png)

Does it work for development build ?

**Comment by Unixon-solutions** [comment]
I got VOIP notification for development build.
but app getting crash because data is null.

Can you help me why getting null data ?

**Comment by DaveLomber** [comment]
ok then if you subscribe for development but send a push to live - it will not work 

Same env should be used 

Re crash - please provide more info, what exactly is crashing, a stacktrace would be helpful

**Comment by Unixon-solutions** [comment]
I have handled crash issue, it was due to null data.
I was sending voip push from ConnectyCube admin panel which was not sending data as app was receiving that's why it was getting crash

Can I send voip push using` ConnectyCube.pushnotifications.events.create `?
I have tried but its not working. Can you please explain me how can I send voip push?

**Comment by DaveLomber** [comment]
@Unixon-solutions yes you can do it

Please check this link https://developers.connectycube.com/js/push-notifications?id=voip-push-notifications
