### ISSUE TITLE
Websocket is down

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#27]
Hey guys, we have noticed that chat/calls are down for our website: https://jwperfectmatch.com/ in PRODUCTION.

Could you help us with that, since we have a lot of emails from our customer ;(

See screenshot below.

![image](https://user-images.githubusercontent.com/4874090/82624782-b3b0c300-9ba0-11ea-82cf-a8089695d593.png)

**Comment by DaveLomber** [comment]
Hi  @masmerino13 

Thank you for contacting ConnectyCube 

There was an outage with ConnectyCube Chat Service.
We received a huge spike in CPU load in ConnectyCube Chat Service at Shared instance in ~4h ago, 
which caused a performance degradation and in the end - service down 

For now - ConnectyCube Chat Service is restored, 
we are closely monitoring all the services  
and the team is analysing the situation to apply all the required remedies 

Sorry of any inconvenience 

Should you have any questions - please let us know
