### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.jid._local')

### ISSUE THREAD

**Issue by Unixon-solutions** [ConnectyCube/connectycube-js-sdk-releases#28]
Hello 

I got this error sometimes due to which video call does not work

**IOS Safari**
TypeError: null is not an object (evaluating 'e.jid._local')

**Android Chrome** 
Uncaught TypeError: Cannot read property '_local' of null

![Screenshot 2020-05-23 at 7 28 38 PM](https://user-images.githubusercontent.com/47319424/82732578-ab38c380-9d2b-11ea-8535-e068fb352730.png)

Please let me know what is causing this error

Thanks

**Comment by ccvlad** [comment]
Make sure that you have logged in and connected to chat. The error related to the chat connection. The chat does not know the user's identifier (jid)

**Comment by Unixon-solutions** [comment]
Is it required to login before connecting to Chat ?
OR I can call them simultaneously

**Comment by ccvlad** [comment]
For the XMPP chat connection - **ConnectyCube.chat.connect(userParams)**.
To create and set a ConnectyCube session for feature calls to REST API - **ConnectyCube.createSession(userParams)**.

**ConnectyCube.createSession()** and then **ConnectyCube.chat.connect()**

**Comment by Unixon-solutions** [comment]
My steps. are 
` ConnectyCube.createSession().then`
`ConnectyCube.chat.connect(userData).then`

This error occurred when there is already an incoming call before chat got connected.

**Comment by ccvlad** [comment]
I have never reproduced the case. Usually incoming call comes after connection already exist. Are the any steps to reproduce? Could show more logs above the error?

**Comment by Unixon-solutions** [comment]
When I call to a device which has app closed so when it start to connect with chat it already has an incoming call.

These are logs when I got this error.
[connectyciubeLogs..txt](https://github.com/ConnectyCube/connectycube-js-sdk-releases/files/4676588/connectyciubeLogs.txt)

**Comment by ccvlad** [comment]
Try to do ConnectyCube.chat.disconnect() before you close the app. Which SDK version do you use? Is it in browser?

**Comment by Unixon-solutions** [comment]
I am using 2.1.6 or 2.1.7 version.
Getting issue in iOS and Android Cordova app.

**Comment by ccvlad** [comment]
> My steps. are
> ` ConnectyCube.createSession().then`
> `var userData = { userId: userID, password: session.token };`
> `ConnectyCube.chat.connect(userData).then`
> 
> This error occurs when connecting to chat.
> This error occurs when there is already an incoming call before chat got connected.
> This error occurs only sometime

Is your app in background mode or killed before the moment? Can I reproduce the issue on our [VideoChat cordova sample](https://github.com/ConnectyCube/connectycube-cordova-samples/tree/master/sample-videochat-cordova)?

**Comment by Unixon-solutions** [comment]
Not able to reproduce in VideoChat cordova sample App.

My app is killed when I receive a call notification which open app and then create session,  login with username and token and connect to chat automatically.

Sometime it connect and sometimes I got this error.

If you let me know what can cause this error I will rectify it.

Thanks

**Comment by nocodedweb** [comment]
After additional testing, we receive a 10% failure rate on incoming calls received to devices where our app is killed (not open in any way) on the device.

We run createSession() method, then login(), then chat.connect() through ConnectyCube JavaScript API.

On chat.connect() method, the script stops dead, no callback method fired, after trying to access e.jid._local variable on line 996 of the JavaScript API script.  e.jid is null, which looks to be the Jabber ID/object created for the XMPP server communication.

We've stepped through our application to ensure that everything is passed correctly to your JavaScript API, but error still remains intermittently.

Let us know what you find on this issue.

**Comment by vo-va** [comment]
I am experiencing same issue, but in slightly different situation. 
In my situation Cordova Application does not receiving incoming calls when app was switched to background mode and then back to foreground mode.
I am using Cordova event 'resume', that allow me to execute code when app switched to foreground. Inside `resume` handler I am executing next code

```
ConnectyCube.chat.disconnect();
ConnectyCube.chat.connect(...);
```
It is not helping and in JS console I am seeing `e.jid.__local` error.

 
Also @ccvlad can I ask you to update connectycube-cordova-samples code to show us not obfuscated main.js code. I don't need to see library code I want to see how you using ConnectyCube library.

**Comment by ccvlad** [comment]
1. We will try to reproduce the `e.jid.__local` error and find solution. Will keep you updated.
2. "obfuscated main.js code in connectycube-cordova-samples" - I will discuss with our team. We use the single JS file just for Cordova's samples. Also we have a [guide](https://developers.connectycube.com/cordova/code-samples?id=do-it-yourself) how to build Cordova's samples from usual [connectycube-web-samples](https://github.com/ConnectyCube/connectycube-web-samples).

**Comment by DaveLomber** [comment]
@vo-va  re Cordova - it's using the Web code samples src code, 
so all src code is available here https://github.com/ConnectyCube/connectycube-web-samples

and here are the guides how we build Cordova samples from Web samples:
https://developers.connectycube.com/cordova/code-samples?id=do-it-yourself

We will think how to make it easier

**Comment by DaveLomber** [comment]
@Unixon-solutions I did a more deep investigation

and it seems indeed we have an issue related to race conditions, 
when a message can be received between XMPP auth and resource binding requests 

cause user's jid is available only after resource binding 
https://github.com/xmppjs/xmpp.js/blob/master/packages/resource-binding/index.js#L19

so If a message comes before resource binding then to can cause the mentioned issue

Let me think what we can do here

**Comment by DaveLomber** [comment]
We have prepared a fix for the issue, 
the new release will be pushed during next 1-2 days

**Comment by ccvlad** [comment]
Hi there!
Try to update SDK.
The issue was fixed in the [ConnectyCube SDK v3.1.0](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.1.0)

**Comment by Unixon-solutions** [comment]
This link is not working
https://cdn.jsdelivr.net/npm/connectycube@3.1.0/dist/connectycube.min.js

**Comment by DaveLomber** [comment]
@Unixon-solutions updated

**Comment by Unixon-solutions** [comment]
https://api.connectycube.com/login.json

`{"login":"hookspot_1588830114_155179491","password":"db4746ad4716fadf41671b2be5cbb6df9c0008f1"}`

Bad Authentication data. Unauthorized on remote side. SSL Error

Getting above error when trying to login in both old and new version sdk.

**Comment by nocodedweb** [comment]
Unable to log into the ConnectyCube admin console, which appears to be causing issues logging into chat as well.  Can you confirm?

![cc-issue](https://user-images.githubusercontent.com/20359577/83527997-caf78680-a4a5-11ea-9683-0ab78e0ad195.jpg)

**Comment by DaveLomber** [comment]
@nocodedweb we are investigation for the reason 
please refer for more updates 
https://connectycube.com/2020/06/02/shared-cloud-instance-unavailable-issue-admin-connectycube-com-2/

**Comment by nocodedweb** [comment]
Does this include issues with login.json REST API call?  Our backend script was working fine up until this issue came up.

**Comment by DaveLomber** [comment]
@nocodedweb  no it does not, as this is something unrelated 

As I understand you use Custom mIdentity Provider feature? 
If yes - seems your external API for session validation has an issue with SSL certificate 

Could you please check

**Comment by nocodedweb** [comment]
Correct.  We've had this setup for weeks now and it was working fine until this morning when we weren't able to log into the ConnectyCube admin.  We receive the above error.  No changes made to our script or to the SSL certificates.  Was something changed on ConnectyCube's end that would cause this error?

**Comment by DaveLomber** [comment]
@nocodedweb this is definitely something with SSL at your end

Here is what I got when do a curl for your verification endpoint:


```
$ curl -X POST https://www..../resp.php

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by nocodedweb** [comment]
Our installed SSL certificate for domain shows it doesn't expire until 2021:

![hk-ssl](https://user-images.githubusercontent.com/20359577/83560842-16288e00-a4d4-11ea-9940-01f57cc61368.png)

**Comment by DaveLomber** [comment]
@nocodedweb understood it
but what I can say so far  - both backend and my local machine (when using curl) says it's not valid 

I'm trying to get more info 

Could you also please try curl from your local machine and see how it works

**Comment by DaveLomber** [comment]
It might be something wrong with a certificate chain, e.g. not with certificate itself, but with a root certificate 

Please read this thread  https://stackoverflow.com/questions/62107431/curl-error-60-ssl-certificate-problem-certificate-has-expired

**Comment by nocodedweb** [comment]
Re-issuing the certificate fixed the SSL issue.

**Comment by Unixon-solutions** [comment]
> @Unixon-solutions updated

Now this error is not occurring.

Thanks.
