### ISSUE TITLE
Chat group implementation

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#29]
Hey guys,

I'm doing a new CN implementation, but I'm not sure what i'm doing wrong, seems i'm ws connected, also the *onSentMessageCallback* is listening BUT I don't see the messages stored in my group chat, this is the second time that I use CN and I'm not sure what i'm doing wrong, also I tried to follow the example app that you have on this repo.

I'm using
create-react-app

The flow that i'm implementing
1. User signup (auto login)
2. Create group chat
3. Join to the group
4. Connect to chat
5. Send message

![image](https://user-images.githubusercontent.com/4874090/84201115-07f2e880-aa65-11ea-9945-95602aca33ed.png)

**Comment by DaveLomber** [comment]
Hi @masmerino13 

First of all, you can skip the room join, as recently we deprecated the API and marked is not required 

Also, 
I see there is something wrong with the 'to' attribute when send a message, 

Could you please provide a code snippet how you perform a message send, it will help to understand what's missing

**Comment by masmerino13** [comment]
Thanks, I have removed the join method.

This is my send message method, in the *to* attr there it is the dialog id, since this is a group chat
![image](https://user-images.githubusercontent.com/4874090/84400095-d8f08a00-abbe-11ea-9d90-e3678809e514.png)

Thanks!

**Comment by DaveLomber** [comment]
@masmerino13 I guess I found an issue in SDK.. 

Sending a message to group chat by dialog id does not work, only by dialog room jid...

If this is a group chat - please try to use the following:

```
const dialogJid = ConnectyCube.chat.helpers.getRoomJidFromDialogId(dialog.id);
ConnectyCube.chat.send(dialogJid, message)
```

we will fix the issue in the upcoming release 

Thanks for reporting !

**Comment by masmerino13** [comment]
Thank you @DaveLomber , that works!

**Comment by DaveLomber** [comment]
Also with latest release it should work by dialog ID as well

https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.7.5
