### ISSUE TITLE
Create public chat group or join to a private group

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#30]
Hey guys, I have this scenario.

A user request support/assistance by doing a question, to achieve this we are creating a chat dialog by each question.

So, to answer the question the support member have to join to the chat dialog and start the chat.

Actually we are creating chat dialogs of `type: 2` BUT then the support member try to join there is an error that saids he don't have permissions to do that, how we should achieve this?
```
{"errors":["You don't have appropriate permissions to perform this operation"]}
```

The other option is to create public chat groups `type: 1` since any user can join with out permissions requirements, BUT when we try to create public dialogs there an error that saids:
```
{"errors":["You do not have appropriate permissions. Broadcast dialogs can be created only via Admin panel."]}
```

Any help is welcome, thanks

**Comment by DaveLomber** [comment]
1) Chat with `type: 2` is a private group chat, where only chat occupants can add new users into it

Some more info can be found here https://developers.connectycube.com/server/chat?id=roles-and-privileges 

2) To create a public chat you need to pass `type: 4`

3) Another option can be to still use private group chats  `type: 2`, but a user should add support member when create a chat (it can be managed under the hood), so a real end user just creates a chat, but in app code you create a chat with support member(s)
