### ISSUE TITLE
Contact list subscribe listeners error

### ISSUE THREAD

**Issue by BilalQadar** [ConnectyCube/connectycube-js-sdk-releases#31]
Hi, 
I am using the `ContactList` feature to create a friend request system in react-native. Currently having an issue where whenever the `onConfirmSubscribeListener` or the `onRejectSubscribeListener` are called the following error appears. 

`Error: "contact" is read-only`

Note that the `onSubscribeListener` and the `onContactListListener` work as intended.

**Comment by BilalQadar** [comment]
Just following up, has any progress been made towards finding the root of this issue?

**Comment by DaveLomber** [comment]
Hi @BilalQadar 
appologize for the delayed reply 

We have double checked the source code and did not find any reason of the issue

1) the sdk spec tests working fine 
2) the `contact` itself is defined via `let` - `let contact = this.contactList.contacts[userId];` in both these callback 

Could you please provide a console log or screenshot of the error 

Also please double check your implementations of `onConfirmSubscribeListener` and `onRejectSubscribeListener` - maybe you have some `const` usage here

**Comment by BilalQadar** [comment]
Hi, no worries for the delay. I spent some time checking for `const` usage. Even after changing everything to `let` I still have the same issue. Below is how the subscribe listeners are implemented. The code below is in the chatService.js file from the react-native sample project provided by ConnectyCube. 

```
setUpListeners() {
    ConnectyCube.chat.onRejectSubscribeListener = this.onRejectSubscribeListener.bind(this)
    ConnectyCube.chat.onConfirmSubscribeListener = this.onConfirmSubscribeListener.bind(this)
}
```

The binded functions as of now just print out that the listener was called. The `setUpListener()` is called when a user logs in. However, whenever these listeners are called due to an another user confirming or rejecting a request the following error appears. 

```
Error: "contact" is read-only
_readOnlyError
    readOnlyError.js:2:18
ChatService#_onPresence
    cubeChat.js:706:51
callbackStanza
    cubeChat.js:144:27
emit
    events.js:152:17
Connection#_onElement
    index.js:99:14
_onElement
    [native code]:0
emit
    events.js:152:17
onEndElement
    FramedParser.js:36:16
onEndElement
    [native code]:0
emit
    events.js:152:17
_handleTagOpening
    ltx.js:40:16
write
    ltx.js:159:35
write
    Parser.js:71:22
Connection#_onData
    index.js:49:22
_onData
    [native code]:0
emit
    events.js:152:17
EventTarget.prototype.dispatchEvent
    event-target-shim.js:818:39
_eventEmitter.addListener$argument_1
    WebSocket.js:232:27
emit
    EventEmitter.js:190:12
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by DaveLomber** [comment]
Thanks, the stack trace is really useful!

the last question to shed some light over it - what RN SDK version is used?

**Comment by BilalQadar** [comment]
```
react-native-cli: 2.0.1
react-native: 0.61.5
```
Using ConnectyCube JS SDK v2

Thanks!

**Comment by DaveLomber** [comment]
@BilalQadar ok then it's clear now

In prev SDK version V2 it was a `const` modifier 
which is ok now in V2 `let`

Please upgrade to V3, 
you should be totally safe doing so, as it only introduces new Conferencing API

**Comment by BilalQadar** [comment]
@DaveLomber I upgraded `react-native-connectycube` to version`3.0.2`. I am still however getting the same error described above.

**Comment by DaveLomber** [comment]
so strange, 
We just double checked 3.0.2
`node_modules/react-native-connectycube/lib/messaging/cubeChat.js` line 669 

and it's
`let contact = this.contactList.contacts[userId];` 

so it's not a `const` here

Could you please do the following:
- make user you use SDK v3 not less 
- please check same file `cubeChat.js` that you see here `let` as well
- also, please add more logs inside `cubeChat.js` and see where it crashes - and report, this will help us a lot to check what's going on 

Thank you
