### ISSUE TITLE
iOS Safari error: "TypeError: Attempted to assign to readonly property."

### ISSUE THREAD

**Issue by nocodedweb** [ConnectyCube/connectycube-js-sdk-releases#33]
Hello.  I'm having some trouble getting the JavaScript API to work in iOS Safari using a PWA solution.  When I initiate a call from another device, The incoming call notification is received.  When I accept the call with:

`video_session.accept({});`

I get the following error:

`TypeError: Attempted to assign to readonly property. :connectycube.min.js:2:36578`

Using 3.3.0 of the JavaScript API.

The error always happens when I call the .accept() method on the session.  I'm running on an iPhone 8 with iOS version 13.6.  WebRTC is enabled in my Safari settings.  Let me know if you need more info than this.  It happens specifically at this part, so wasn't sure.

**Comment by DaveLomber** [comment]
@nocodedweb  do you face the same here
https://connectycube.github.io/connectycube-web-samples/videochat/dist/

?

it's a live demo of https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat

**Comment by nocodedweb** [comment]
Your sample app seems to work fine on both Android and iOS PWA's.  Will reference that.

**Comment by DaveLomber** [comment]
@nocodedweb could you please share what was the root cause of the issue?
Would be great to have for future refs 

Thank you

**Comment by DaveLomber** [comment]
We have finally reproduced an issue and fixed it in SDK 3.5.1
