### ISSUE TITLE
ConnectyCube Authentication With Refresh Token

### ISSUE THREAD

**Issue by stephanoparaskeva** [ConnectyCube/connectycube-js-sdk-releases#35]
Does ConnectyCube offer one of these two options:

1) ConnectyCube refresh token to be available in my app so I can keep user logged in and check that they are logged in to connectycube when they do things that do not need to use connectycube api?
 - Eg a user logs in to my app, they get verified by my back-end and given access token and refresh token. 
 - User uses my app but does not make any calls so token begins expiring. When user makes general request (/myapi/categories) the /refresh endpoint is hit and they are kept logged into connectycube

2) Or can ConnectyCube provide a way to connect with my EXISTING Refresh/Access token authentication (note I need refresh token as well to keep user logged in) and to access this myself in my own backend?

P.s.
Can we change token expiration time?

```
access token that is valid for 2 hours this gets renewed every time user uses the connectycube api
```
This is absurd ^ needs refresh token so user does not have to keep logging in, and so user sessions are secure

**Comment by banshiAnton** [comment]
Hi @stephanoparaskeva you can use this callback
https://developers.connectycube.com/js/authentication-and-users?id=session-expiration
In this callback you can create new session if your is expired
Out team always use this callback and don't care about session TTL

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva you can use this callback
> https://developers.connectycube.com/js/authentication-and-users?id=session-expiration
> In this callback you can create new session if your is expired
> Out team always use this callback and don't care about session TTL

No. I am talking about Refresh Tokens. My back-end users Refresh-Tokens for user security. I need to be able to connect with this. I need Refresh Token endpoint for connectycube so that I can refresh the user AccessToken and store it . How is this working 'Automatically' and how do I ensure that I can keep user logged in, while keeping user Security?

This endpoint doesn't tell me much.

**Comment by banshiAnton** [comment]
Unfortunately we don't have API for refresh token, you can only create new session

**Comment by stephanoparaskeva** [comment]
> Unfortunately we don't have API for refresh token, you can only create new session

Ok, but how does this work? Do you provide access token? new login details? 

How is this secure for the user?

How do I best integrate it with my refresh-token flow currently?

I cannot seem to get this all from the docs and so would love if you could help answer these and explain this to me

**Comment by banshiAnton** [comment]
Of course every session has token
In this callback you can create new session and retry your request
https://developers.connectycube.com/js/authentication-and-users?id=session-expiration

**Comment by stephanoparaskeva** [comment]
> Of course every session has access token
> In this callback you can create new session and retry your request
> https://developers.connectycube.com/js/authentication-and-users?id=session-expiration

Can you give an explanation please, I am not sure how this works.

I would like to know what this callback allows me to do. Every time user sends a request with an expired token, this callback is called and what do you do then?

* Do you provide login details of the user again? if you do, does this mean you must store these somewhere, like local storage?
* Does it happen automatically by providing access token? If it does, how is this secure for the user?

How do you keep user logged in, while making this secure, and how do you do this when you have already configured your backend to utilise *refresh tokens* for your app?

**Comment by banshiAnton** [comment]
Yes need provide  login details of the user again and create new cession in this callback
Yes you can encrypt user credentials and store in local storage

**Comment by stephanoparaskeva** [comment]
> Yes you need to provide login details of the user again and create new session in this callback
> Yes you can encrypt user credentials and store in local storage

No man, this is very very insecure. That's wrong. 
Is there a way to issue new tokens after expiration automatically without needing user credentials again?

**Comment by banshiAnton** [comment]
@stephanoparaskeva now our platform  does not have other way to create new session after old is expired

**Comment by stephanoparaskeva** [comment]
> @stephanoparaskeva now our platform does not have other way to create new session after old is expired

So everyone that uses the platform has to use login details (username & password) every 2 hours?

**Comment by ccvlad** [comment]
Hi @stephanoparaskeva 

Our API doesn't provide refresh token.
After first login user is able to store the session token and use it within two hours for [init ConnectyCube SDK with existing token](https://developers.connectycube.com/js/?id=initialize-with-existing-token).
User also can restore the expired session in the [sessionExpired callback](https://developers.connectycube.com/js/authentication-and-users?id=session-expiration) while use the application.
User have to use login params again if he/she has expired token and is trying to login (you've been right - encrypted 
 login/email + password in asyncstorage/localstorage/DB)

**Comment by stephanoparaskeva** [comment]
> Hi @stephanoparaskeva
> 
> Our API doesn't provide refresh token.
> After first login user is able to store the session token and use it within two hours for [init ConnectyCube SDK with existing token](https://developers.connectycube.com/js/?id=initialize-with-existing-token).
> User also can restore the expired session in the [sessionExpired callback](https://developers.connectycube.com/js/authentication-and-users?id=session-expiration) while use the application.
> User have to use login params again if he/she has expired token and is trying to login (you've been right - encrypted
> login/email + password in asyncstorage/localstorage/DB)

Ah so user must ONLY be able to restore expired session with email + password from asyncstorage etc?

This is very insecure though lol

**Comment by ccvlad** [comment]
no other way

**Comment by stephanoparaskeva** [comment]
k

> no other way

^

**Comment by stephanoparaskeva** [comment]
> no other way

Edited above ^
This does not make sense. So you send login details every 2 hours?

**Comment by ccvlad** [comment]
If the session was expired and user still use the app, he/she also is able to use sessionExpired cb to restore the session and retry the last API request.
If user would login after 2 hours (application was closed more than 2 hours), he/she have to repeat the login flow or autologin with previously stored params.

**Comment by stephanoparaskeva** [comment]
kk

> If the session was expired and user still use the app, he/she also is able to use sessionExpired cb to restore the session and retry the last API request.

How does this part work?

**Comment by ccvlad** [comment]
> > no other way
> 
> Edited above ^
> This does not make sense. So you send email + password every 2 hours?

No. It just necessary flow for this case: "If user would login after 2 hours (application was closed more than 2 hours), he/she have to repeat the login flow or autologin with previously stored params."

**Comment by stephanoparaskeva** [comment]
Ohhhhhhhhhhhhhhhhh.

So I can forget about login.

So how to keep user session going without making login, how to do this with:
```If the session was expired and user still use the app, he/she also is able to use sessionExpired cb to restore the session and retry the last API request.```

**Comment by ccvlad** [comment]
> I see.
> 
> > If the session was expired and user still use the app, he/she also is able to use sessionExpired cb to restore the session and retry the last API request.
> 
> How does this part work?

```javascript
const CONFIG = {
  on: {
    sessionExpired: (handleResponse, retry) => {
      // call handleResponse() if you do not want to process a session expiration,
      // so an error will be returned to origin request

      ConnectyCube.createSession()
        .then(retry)
        .catch((error) => {});
    },
  },
};

ConnectyCube.init(CREDENTIALS, CONFIG);
```

**Comment by ccvlad** [comment]
> Ohhhhhhhhhhhhhhhhh.
> 
> So I can forget about login.
> 
> So how do you keep user session going ~3 months?, without making login, how to do this with this:
> `If the session was expired and user still use the app, he/she also is able to use sessionExpired cb to restore the session and retry the last API request.`

Just repeat to you - if user would login after 2 hours (application was closed more than 2 hours), he/she have to repeat the login flow or autologin with previously stored params.

**Comment by stephanoparaskeva** [comment]
I see. That is not good at all.

**Comment by ccvlad** [comment]
> I see. That is not good at all.

That is, do you understand how it works?

**Comment by stephanoparaskeva** [comment]
> > I see. That is not good at all.
> 
> That is, do you understand how it works?

Yes, 
* User logs in
* Save details
* Make call
* wait 2 hours
* User must login again or app must retrieve/decrypt login details from async storage.

This is insecure because:
* Client will be making network requests with Login+Password multiple times daily. This means these are very vulnerable to being stolen.

* Client will store login details so these are vulnerable to attacks, and theft.

This is not useable for my usecase.

Thank you for the help. And if there is another way to do it, I'd love to know.
