### ISSUE TITLE
Error with V0.63.1

### ISSUE THREAD

**Issue by cnazha** [ConnectyCube/connectycube-js-sdk-releases#37]
Hello
Getting the following error when importing Connecty Cube to RN V0.63.1:
```
ExceptionsManager.js:179 Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```
![Simulator Screen Shot - iPhone 11 - 2020-07-17 at 13 18 30](https://user-images.githubusercontent.com/9191952/87776221-18e70480-c830-11ea-9f68-696c4487e976.png)

**Comment by Kachanov-dev** [comment]
Hi @cnazha.
Could you add the dependency `pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc' ` to the Podfile, then  do `cd ios && rm -rf Pods && rm -rf Podfile.lock && pod install`.
Please write if it doesn't work ?

**Comment by cnazha** [comment]
Works, here is what I did:

- Added the webrtc dependency to pod
```
pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
```

- Deleted Podfile.lock
```
rm -rf Podfile.lock
```

- Updated ios deployment target to 11 from 10 in podfile, since react-native-webrtc required a higher minimum deployment target
```
platform :ios, '11.0'
```

Thanks @Kachanov-dev
