### ISSUE TITLE
'setRemoteSessionDescription' error: failed to set remote answer sdp: called in wrong state: kstable

### ISSUE THREAD

**Issue by jayeshgurudayalani** [ConnectyCube/connectycube-js-sdk-releases#38]
i have tried to perform p2p video call 
when i try to make 1-1 video call it is working fine but when i try to make 1- many video call and opponent person accept video calling that time it shows me this error 
`'setRemoteSessionDescription' error: failed to set remote answer sdp: called in wrong state: kstable`

`"react-native-connectycube": "^3.2.0",
"react": "16.9.0",
 "react-native": "0.61.5",`

Note :- I have not purchased any plan.

here is my code

this is screen which is shown when someone make video call

`
import React, {Component} from 'react';
import {View, Modal, Image} from 'react-native';
import Touchable from 'react-native-platform-touchable';
import ConnectyCube, {RTCView} from 'react-native-connectycube';
import {
  heightPercentageToDP,
  widthPercentageToDP,
} from 'react-native-responsive-screen';
import * as GColors from '../../common/GColors';
import SessionManager from '../../APIClass/SessionManager';
import {EventRegister} from 'react-native-event-listeners';
import {EventsNames} from '../../common/GConstants';
import InCallManager from 'react-native-incall-manager';

export default class VideoCallReceiverModal extends Component {
  constructor(props) {
    super(props);

    this.state = {
      isVisible: false,
      session: undefined,
      isReceived: false,
      userId: '',
      remoteStreamsArr: [],
    };

    this.getReceivingVideoCallView = this.getReceivingVideoCallView.bind(this);
    this.onRemoteStreamReceived = this.onRemoteStreamReceived.bind(this);
    this.getReceivedVideoCallView = this.getReceivedVideoCallView.bind(this);
    this.showVideoCall = this.showVideoCall.bind(this);
    this.getRTCView = this.getRTCView.bind(this);
    this.acceptCall = this.acceptCall.bind(this);
  }

  render() {
    InCallManager.setSpeakerphoneOn(
      this.state.remoteStreamsArr.length > 0 ? true : false,
    );

    return (
      <Modal
        transparent={true}
        animationType="slide"
        visible={this.state.isVisible}>
        {this.state.isReceived && this.state.remoteStreamsArr.length > 0
          ? this.getReceivedVideoCallView()
          : this.getReceivingVideoCallView()}
      </Modal>
    );
  }

  getReceivingVideoCallView = () => {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: 'flex-end',
          alignItems: 'center',
          backgroundColor: GColors.colorWhite,
        }}>
        <View
          style={{
            flexDirection: 'row',
            marginBottom: heightPercentageToDP('5%'),
          }}>
          <Touchable
            style={{
              paddingVertical: heightPercentageToDP('2%'),
              paddingHorizontal: widthPercentageToDP('2%'),
            }}
            activeOpacity={0.5}
            onPress={() => {
              this.acceptCall();
            }}>
            <Image
              resizeMode="contain"
              source={require('../../../assets/images/outgoing_call_icon.png')}
            />
          </Touchable>
          <View style={{width: widthPercentageToDP('50%')}} />
          <Touchable
            style={{
              paddingVertical: heightPercentageToDP('2%'),
              paddingHorizontal: widthPercentageToDP('2%'),
            }}
            activeOpacity={0.5}
            onPress={() => {
              if (this.state.session) {
                this.state.session.reject({});
              }
            }}>
            <Image
              resizeMode="contain"
              source={require('../../../assets/images/incoming_call_icon.png')}
            />
          </Touchable>
        </View>
      </View>
    );
  };

  getReceivedVideoCallView = () => {
    console.log(
      '=-=-=-=-=-=-=-=-=-=-=-= getReceivedVideoCallView -=-=-=-=--=-=-=-=',
    );
    console.log('remote arr ' + JSON.stringify(this.state.remoteStreamsArr));
    return (
      <View style={{flex: 1}}>
        {this.getRTCView()}

        <View
          style={{
            position: 'absolute',
            width: widthPercentageToDP('100%'),
            height: heightPercentageToDP('90%'),
            backgroundColor: GColors.colorTransparent,
            justifyContent: 'flex-end',
            alignItems: 'center',
          }}>
          <Touchable
            style={{marginBottom: heightPercentageToDP('5%')}}
            activeOpacity={0.5}
            onPress={() => {
              if (this.state.session) {
                this.state.session.stop({});
                this.setState(this.getStateInitialObj());
              }
            }}>
            <Image
              resizeMode="contain"
              source={require('../../../assets/images/incoming_call_icon.png')}
            />
          </Touchable>
        </View>
      </View>
    );
  };

  showVideoCall = session => {
    this.setState({session: session, isVisible: true}, () => {
      const mediaParams = {
        audio: true,
        video: true,
        options: {
          muted: false,
          mirror: true,
        },
      };

      session
        .getUserMedia(mediaParams)
        .then(localStream => {})
        .catch(error => {});
    });
  };

  setRemoteStreamListener() {
    console.log('=======================remote stream set');
    ConnectyCube.videochat.onRemoteStreamListener = this.onRemoteStreamReceived;
    this.setState({userId: SessionManager.getConnectyCubeUser().id});
  }

  onRemoteStreamReceived = (session, userID, remoteStream) => {
    console.log(
      '============================= onRemoteStreamReceived ===========================',
    );
    let remoteStreamsArr = this.state.remoteStreamsArr;

    console.log('remote streams Arr ' + JSON.stringify(remoteStreamsArr));
    console.log('userid ' + userID);

    let remoteStreamIndex = remoteStreamsArr.findIndex(
      item => item.userId == userID,
    );

    console.log('userid pos ' + remoteStreamIndex);

    if (remoteStreamIndex != -1) {
      let item = remoteStreamsArr[remoteStreamIndex];
      item['remoteStream'] = remoteStream;
      remoteStreamsArr[remoteStreamIndex] = item;
    }
    this.setState({remoteStreamsArr: remoteStreamsArr});
  };

  componentWillMount() {
    this.listener = EventRegister.addEventListener(
      EventsNames.CONNECTYCUBE_CONNECTION_STATE_CHANGE,
      data => {
        if (
          data.connectionState ==
          ConnectyCube.videochat.SessionConnectionState.CLOSED
        ) {
          let remoteStreamsArr = this.state.remoteStreamsArr;
          let newRemoteStreamsArr = remoteStreamsArr.filter(
            item => item.userId != data.userID,
          );

          console.log('old remote streams ' + JSON.stringify(remoteStreamsArr));
          console.log(
            'new remote streams ' + JSON.stringify(newRemoteStreamsArr),
          );

          if (newRemoteStreamsArr.length > 0) {
            this.setState({remoteStreamsArr: newRemoteStreamsArr});
          } else {
            this.setState(this.getStateInitialObj());
          }
        }
      },
    );
  }

  componentWillUnmount() {
    if (this.listener) {
      EventRegister.removeEventListener(this.listener);
    }
  }

  getStateInitialObj() {
    return {
      isVisible: false,
      session: undefined,
      isReceived: false,
      userId: '',
      remoteStreamsArr: [],
    };
  }

  getRTCView() {
    let remoteStreamsNotUndefinedArr = this.state.remoteStreamsArr;
    switch (remoteStreamsNotUndefinedArr.length) {
      case 1:
        return (
          <RTCView
            objectFit="cover"
            key={remoteStreamsNotUndefinedArr[0].userId}
            style={{flex: 1}}
            streamURL={
              remoteStreamsNotUndefinedArr[0].remoteStream
                ? remoteStreamsNotUndefinedArr[0].remoteStream.toURL()
                : ''
            }
          />
        );

      case 2:
        return (
          <View style={{flex: 1, flexDirection: 'row'}}>
            <RTCView
              objectFit="cover"
              key={remoteStreamsNotUndefinedArr[0].userId}
              style={{flex: 1}}
              streamURL={
                remoteStreamsNotUndefinedArr[0].remoteStream
                  ? remoteStreamsNotUndefinedArr[0].remoteStream.toURL()
                  : ''
              }
            />
            <RTCView
              objectFit="cover"
              key={remoteStreamsNotUndefinedArr[1].userId}
              style={{flex: 1}}
              streamURL={
                remoteStreamsNotUndefinedArr[1].remoteStream
                  ? remoteStreamsNotUndefinedArr[1].remoteStream.toURL()
                  : ''
              }
            />
          </View>
        );

      case 3:
        return (
          <View style={{flexDirection: 'column', flex: 1}}>
            <View style={{flex: 1, flexDirection: 'row'}}>
              <RTCView
                objectFit="cover"
                key={remoteStreamsNotUndefinedArr[0].userId}
                style={{flex: 1}}
                streamURL={
                  remoteStreamsNotUndefinedArr[0].remoteStream
                    ? remoteStreamsNotUndefinedArr[0].remoteStream.toURL()
                    : ''
                }
              />
              <RTCView
                objectFit="cover"
                key={remoteStreamsNotUndefinedArr[1].userId}
                style={{flex: 1}}
                streamURL={
                  remoteStreamsNotUndefinedArr[1].remoteStream
                    ? remoteStreamsNotUndefinedArr[1].remoteStream.toURL()
                    : ''
                }
              />
            </View>
            <RTCView
              objectFit="cover"
              key={remoteStreamsNotUndefinedArr[2].userId}
              style={{flex: 1}}
              streamURL={
                remoteStreamsNotUndefinedArr[2].remoteStream
                  ? remoteStreamsNotUndefinedArr[2].remoteStream.toURL()
                  : ''
              }
            />
          </View>
        );

      case 4:
        return (
          <View style={{flexDirection: 'column', flex: 1}}>
            <View style={{flex: 1, flexDirection: 'row'}}>
              <RTCView
                objectFit="cover"
                key={remoteStreamsNotUndefinedArr[0].userId}
                style={{flex: 1}}
                streamURL={
                  remoteStreamsNotUndefinedArr[0].remoteStream
                    ? remoteStreamsNotUndefinedArr[0].remoteStream.toURL()
                    : ''
                }
              />
              <RTCView
                objectFit="cover"
                key={remoteStreamsNotUndefinedArr[1].userId}
                style={{flex: 1}}
                streamURL={
                  remoteStreamsNotUndefinedArr[1].remoteStream
                    ? remoteStreamsNotUndefinedArr[1].remoteStream.toURL()
                    : ''
                }
              />
            </View>
            <View style={{flex: 1, flexDirection: 'row'}}>
              <RTCView
                objectFit="cover"
                key={remoteStreamsNotUndefinedArr[2].userId}
                style={{flex: 1}}
                streamURL={
                  remoteStreamsNotUndefinedArr[2].remoteStream
                    ? remoteStreamsNotUndefinedArr[2].remoteStream.toURL()
                    : ''
                }
              />
              <RTCView
                objectFit="cover"
                key={remoteStreamsNotUndefinedArr[3].userId}
                style={{flex: 1}}
                streamURL={
                  remoteStreamsNotUndefinedArr[3].remoteStream
                    ? remoteStreamsNotUndefinedArr[3].remoteStream.toURL()
                    : ''
                }
              />
            </View>
          </View>
        );
    }
  }

  acceptCall() {
    if (this.state.session) {
      this.state.session.accept({});
      const {opponentsIDs, initiatorID, currentUserID} = this.state.session;

      const opponentsIds = [initiatorID, ...opponentsIDs].filter(
        userId => currentUserID !== userId,
      );

      const remoteStreamsArr = opponentsIds.map(opponentId => {
        return {userId: opponentId, remoteStream: undefined};
      });

      console.log('remotestream init ' + JSON.stringify(remoteStreamsArr));

      this.setState(
        {
          isReceived: true,
          remoteStreamsArr: remoteStreamsArr,
        },
        () => {
          console.log(
            'after set ' + JSON.stringify(this.state.remoteStreamsArr),
          );
        },
      );
    }
  }
}

`

**Comment by ccvlad** [comment]
Hi, @jayeshgurudayalani 
Are you trying to add new participant to the call?

You can use [Multiparty Video Conferencing API](https://developers.connectycube.com/reactnative/videocalling-conference) to add add/remove participants while on a call.

Read more about [Group video calls](https://developers.connectycube.com/js/videocalling?id=group-video-calls)
