### ISSUE TITLE
1.8.0 is not in the CDN or NPM

### ISSUE THREAD

**Issue by pohlman** [ConnectyCube/connectycube-js-sdk-releases#4]
https://cdn.jsdelivr.net/npm/connectycube@1.8.0/dist/connectycube.min.js
^ returns an error, and the NPM version is still using 1.7.3 as well.

This wouldn't be too much of an issue, except the examples in the documentation are using 1.8.0 functions that I don't have access to.

**Comment by DaveLomber** [comment]
Hi @pohlman 

seems an issue happened during our release chain 

Please try 1.8.1 version
https://cdn.jsdelivr.net/npm/connectycube@1.8.1/dist/connectycube.min.js

Thank you for reporting the issue !
