### ISSUE TITLE
About storage

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#40]
Hello guys,

I'm sending images in the chat and i want to know if the storage have a limit?

If true, is possible to remove attachments from a chat dialog using the API?

Thanks

**Comment by ccvlad** [comment]
Hello, @masmerino13 
You can see all limitation here: https://connectycube.com/pricing/
You can mange your data via admin panel.
Also we have the API that you asked:
```javascript
ConnectyCube.storage.delete(fileUID)
  .then(response => console.log(response))
  .catch(error => console.log(error))
```

**Comment by masmerino13** [comment]
thanks @ccvlad do you guys have a way to remove images by dialog id? the thing is that I have chats that expire after sometime and we don't want to preserve the images of those expired chat dialogs, does that make sense?

**Comment by masmerino13** [comment]
this is my scenario.

We have a platform were the moderator should have the ability to delete attachments from messages, BUT this endpoint just allows me to delete the attachment that the logged user sent, the user (moderator) can't delete files that he receive.

Is possible to achieve this with your API?

thanks in advance @ccvlad

**Comment by DaveLomber** [comment]
@masmerino13 this does make sense for sure 👍 
Let me think a bit about it

**Comment by masmerino13** [comment]
Thanks @DaveLomber, I know it is possible from the dashboard, It will be great to do this using the API,

Regards

**Comment by DaveLomber** [comment]
As an idea:
- each attach file in Storage should have a 'dialog_id' field with a ref to chat dialog 
- once a chat dialog is removed - all the connected storage files should be removed automatically as well 

Let me know if it sounds good for you, we will plan the backend feature

**Comment by masmerino13** [comment]
Hi @DaveLomber, what about delete just the attachments and preserve the dialog messages, our platform is about veterinarians service and users pay for the service, we want to preserve the chat history but not the images.

Is this possible?

Thanks in advance

**Comment by DaveLomber** [comment]
If you want to preserve the dialog messages , the you should keep the dialog. 
Otherwise, when delete a chat dialog, all the messages will be removed as well.

So, if you do not remove the chat dialog, hence no messages will be removed as well.
And the only thing we need is API to remove ALL attachments by dialog it. Is this correct?

**Comment by masmerino13** [comment]
That's correct, that would be perfect and pretty helpful for us.

**Comment by DaveLomber** [comment]
In general, we have 2-3 weeks sprints, so we can plan

Just a summary re how it will work:
1) when create & upload a file to storage, it will be possible to pass 'dialog_id' field, just to associate a file with a dialog
2) there will be new API
DELETE https://api.connectycube.com/chat/Dialog/attachments 
to delete all the dialog attachments and it will work according to permissions schema https://developers.connectycube.com/server/chat?id=roles-and-privileges

Could you please confirm this is ok for you? @masmerino13

**Comment by masmerino13** [comment]
yes! sounds good, thank you!

**Comment by masmerino13** [comment]
Do you guys have any updates around that?

**Comment by masmerino13** [comment]
Hi @DaveLomber, do you have any updates about it?

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
