### ISSUE TITLE
How to know if the user is connected to the chat?

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#41]
I need to know if the user is logged in, I was looking through the API but I haven't good luck, any help is welcome

**Comment by DaveLomber** [comment]
1. To check if a user connected to chat:

`ConnectyCube.chat.isConnected`

2. To check if current session is valid:

```
ConnectyCube.getSession()
  .then((session) => {})
  .catch((error) => {});
```

if the token is expired - an error will be raised

**Comment by ccvlad** [comment]
@masmerino13 
Check the doc - https://developers.connectycube.com/js/messaging?id=last-activity-subscription
It is available in chat functionality. So you have to connect the chat before - https://developers.connectycube.com/js/messaging?id=connect-to-chat

**Comment by ccvlad** [comment]
@masmerino13

FYI. If you are talking about listen online status of other users.
Check the doc - https://developers.connectycube.com/js/messaging?id=last-activity-subscription
It is available in chat functionality. So you have to connect the chat before - https://developers.connectycube.com/js/messaging?id=connect-to-chat

**Comment by masmerino13** [comment]
Thanks @ccvlad, yeah, I need to know if the user that I'm sending a message is online, if not, send an email notification.

Thanks!

**Comment by masmerino13** [comment]
Hi @ccvlad, thanks for the info,

I already have the chat and calls working well, but, not sure why this listener `onLastUserActivityListener` doesn't return any info, also not sure if the subscriber (`subscribeToUserLastActivityStatus`) is working, any help is welcome.

thanks a lot

**Comment by DaveLomber** [comment]
@masmerino13 the proper way is to use last activity request 

https://developers.connectycube.com/js/messaging?id=get-last-activity

you can send it to user and receive an immediate response if the user is online or if not, then last activity seconds
