### ISSUE TITLE
Is there a way to send a message with a custom date?

### ISSUE THREAD

**Issue by BilalQadar** [ConnectyCube/connectycube-js-sdk-releases#42]
Hi, 

I need to transfer old user histories. Is there a way to set ```date_sent``` to a custom date object when sending a message. I tried to do this by setting ```date_sent``` in the message object as done in your sample projects. 

```
  let date = Date.parse("2020-06-19T20:45:42-04:00")
  let msg = {
    type: chat.type === 3 ? "chat" : "groupchat",
    body: text,
    extension: {
      save_to_history: 1,
      dialog_id: recipient_id,
      sender_id: user.user_id,
      date_sent: date,
    },
    markable: 1
  }
  msg.id = await connectyCube.chat.send(recipient_id, msg)
```

However, the date which shows up in the admin console is still the actual date and time for when the message was sent.

**Comment by DaveLomber** [comment]
@BilalQadar there is no way to do so, 

cause if you send an invalid param, then the backend will skip it and replace with its own one 

If you ahem any injuries re uploading some backup or so, 
you can ping ConnectyCube via https://connectycube.com/contact/ and provide your backup and additional information what exactly is required
