### ISSUE TITLE
Connection is not offline

### ISSUE THREAD

**Issue by masmerino13** [ConnectyCube/connectycube-js-sdk-releases#46]
Do you know how to handle/avoid this error?

I already have configured the `sessionExpired` callback in the config, also I have configured the `ping` option as well, but it's still happening and I'm not sure what's going on.

Thanks  for your help!

![image](https://user-images.githubusercontent.com/4874090/92418754-714acc00-f126-11ea-8831-43e43b48ab7b.png)

**Comment by banshiAnton** [comment]
Hi @masmerino13 seem that you try connect to chat when your app is not disconnected
Try to call disconnect before create connection (call connect)

**Comment by banshiAnton** [comment]
Hi @masmerino13. Do you have any updates?

**Comment by masmerino13** [comment]
Hey @banshiAnton, this is still happening and doing what you recommend breaks something, btw, I was using the version `2.7.1` because of that I decide to use the last one, but now I'm having another issue (https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/47) ;)

Basically what is happening is that after some time, the WS connection is lost.

Any help is welcome, since I'm close to launch the platform to production and this is like a blocker to achieve this.

Thanks a lot.

**Comment by stevenblake-banntech** [comment]
Did you find a solution to this? I'm currently experiencing the same issue,

**Comment by sukesh-pfx** [comment]
I'm  also experiencing this issue 

![image](https://user-images.githubusercontent.com/64000239/122023473-37110800-cde5-11eb-85a0-bfafb93a9355.png)
