### ISSUE TITLE
web notifications

### ISSUE THREAD

**Issue by aneet48** [ConnectyCube/connectycube-js-sdk-releases#49]
I am using connectycube js sdk with react js project , is it possible to generate web notifications with this ?

**Comment by ccvlad** [comment]
> I am using connectycube js sdk with react js project , is it possible to generate web notifications with this ?

Yes, it is possible, but it would be you own implementation (e.g. you should call Notification/WebNotification after receive a chat message).

FYI, if you about Push Notification, our server does not send Push Notification to Web client.
