### ISSUE TITLE
 ConnectyCube.createSession(user) not working sometimes.

### ISSUE THREAD

**Issue by Vivek1110** [ConnectyCube/connectycube-js-sdk-releases#51]
When I try to login to Connetycube, sometimes it works fine and sometimes it is not working. And throws error like, 
**TypeError: undefined is not an object (evaluating 'this.auth.createSession')**

And below is the code snippet I am using.

  _login = (user) => {
    console.log('this is cube', ConnectyCube)
    return new Promise((resolve, reject) => {
      ConnectyCube.createSession(user)
        .then(() =>
          ConnectyCube.chat.connect({
            userId: user.id,
            password: user.password,
          }),
        )
        .then(resolve)
        .catch(reject);
    });
  };_

**Comment by DaveLomber** [comment]
Hi @Vivek1110 

recently we noticed a performance issue at the backend side
which is resolved now

Please let us know if you still face the issue 

Thanks
