### ISSUE TITLE
promise never went into catch

### ISSUE THREAD

**Issue by chansc2016** [ConnectyCube/connectycube-js-sdk-releases#54]
i have tested the example app, what i was curious is that i have follow the sample code "// JS SDK v2+"

i was trying to catch the error for invalid param but end up not getting into the catch method. Instead i am getting unhandled promise. May i know what am i missing?

  async connect(userId, password) {
    ConnectyCube.chat
  .connect( {userId: 'ggg', password })
  .then(() => {
    console.log('connected')
    // connected
  })
  .catch((error) => {
    console.log(error)   //  <-- trying to catch the error
  });
    //await ConnectyCube.chat.connect({ userId, password })
  }

- react-native : 0.63.3
- react-native-connectycube : 3.7.6
<img width="1382" alt="Screenshot 2020-11-17 at 4 55 50 PM" src="https://user-images.githubusercontent.com/22651091/99368525-34edd600-28f6-11eb-8905-6498e500038e.png">

**Comment by DaveLomber** [comment]
Could you please enable full debug logs via

```
const CONFIG = {
  debug: { mode: 1 }, // enable DEBUG mode (mode 0 is logs off, mode 1 -> console.log())
};
ConnectyCube.init(CREDENTIALS, CONFIG);
```

And provide the logs from the beginning till the error

Thank you

**Comment by chansc2016** [comment]
Hi, just to clarify my question. My purpose is to trigger the .catch for any errors return from the sdk.

    "debug": {
        "mode": 0.        // -< set debug mode off for production
      } 

step to reproduce : 
1) cd connectycube-reactnative-samples
2) cd RNchat
3) in auth-service.js change the connect function to 

  async connect(userId, password) {
    ConnectyCube.chat
    .connect( {userId: 'ggg', password })
    .then(() => {
    console.log('connected')
    // connected
    })
    .catch((error) => {
      console.log('error caught');
      console.log(error); // <--  **Main purpose : trying to catch the error but doesn't went in)**
    });
    //await ConnectyCube.chat.connect({ userId, password })
  }

My expecting result is to get "error caught" string in the debugging console but instead i got unhandled promise.
<img width="1420" alt="Screenshot 2020-11-18 at 11 55 48 AM" src="https://user-images.githubusercontent.com/22651091/99481434-1b4f9b80-2995-11eb-9f1f-a0c5761415a8.png">

**Comment by DaveLomber** [comment]
@chansc2016 we will double check it on our side and get back to you asap

**Comment by DaveLomber** [comment]
@chansc2016 the issue is identified and fixed.
New release will be pushed tomorrow

**Comment by ccvlad** [comment]
@chansc2016 
Please check version 3.7.7 [(release notes)](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/3.7.7)
