### ISSUE TITLE
Firebase Cloud Functions Integration for Chat

### ISSUE THREAD

**Issue by aytunch** [ConnectyCube/connectycube-js-sdk-releases#55]
Hi:)
Through cloud functions, I want to use CC api when a certain thing happens in my Firestore db. I would like to do this by an admin role instead of the cloud functions code pretending to be that user. Right now, my coud functions code uses JS api to;

1. registers a cubeuser (if already registered, logs in the cubeuser)
2. creates a CubeSession with that CubeUser
3. creates a group chat CubeDialog (with a user as an occupant) or adds/removes an Occupant to an existing CubeDialog
4. destroys the CubeSession
5. LogOut the CubeUser

I have some doubts using the Api like this since a cube user might already be logged in from the client and the cloud functions code logging in with the same user might cause some problems. Is this a possible scenario?
Is there anyway I can `register a user`, `create a dialog`, `add occupant`, `remove occupant` without actually logging in as that user? Something like a admin role using the CC api?
I saw something like initing CC with an APPID and a Token. Is this the right way to do what I want? or is it for something else?

**Comment by DaveLomber** [comment]
Hi @aytunch 

There should not be any issue when logic same user from diff places, cause with ConnectyCube it's a common situation when a single user can have multiple active devices/sessions at same time.

There is no Admin API related yet, but we are working on the one one going to push it to the public around Jan 21

As for now, as an alternative solution - you can define one user as a system user and have it in each chat dialog occupants. This might help.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
