### ISSUE TITLE
onMessageListener incomplete cause crash in receiving message

### ISSUE THREAD

**Issue by chansc2016** [ConnectyCube/connectycube-js-sdk-releases#56]
hi, please fix the `onMessageListener` in `chat-service.js` line 178 that the constructor having sender and `sender_id` as null  which will cause crash when receiving message.

```
onMessageListener(senderId, msg) {
    let message = new Message(msg) // <-- change these 3 lines
    message.sender = senderId;   // fix
    message.sender_id = senderId;  // fix
    const user = this.currentUser
    const dialog = this.getSelectedDialog()
    if (senderId !== user.id) {
      if (dialog === message.dialog_id) {
        store.dispatch(sortDialogs(message))
        this.readMessage(message.id, message.dialog_id)
        this.sendReadStatus(msg.extension.message_id, msg.extension.sender_id, msg.dialog_id)
      } else {
        this.sendDeliveredStatus(msg.extension.message_id, msg.extension.sender_id, msg.dialog_id)
        store.dispatch(sortDialogs(message, true))
      }
      store.dispatch(pushMessage(message, message.dialog_id))
    }
  }
```

step to reproduce: 
1) login to user1
2) send message to user2
3) logout and login to user2
4) send message to user1
5) crash occur

<img width="337" alt="Screenshot 2020-11-30 at 1 27 38 PM" src="https://user-images.githubusercontent.com/22651091/100572461-7e83eb00-3310-11eb-9955-70c7f075d21d.png">

**Comment by DaveLomber** [comment]
I'm not sure it's related to these 3 lines 

```
    let message = new Message(msg) // <-- change these 3 lines
    message.sender = senderId;   // fix
    message.sender_id = senderId;  // fix
```

cause the crash relates to a `user` val, not a `message` or `senderId`

Could you please describe in more details this statement: "that the constructor having sender and sender_id as null".
You mean `senderId` param of `onMessageListener` is null?

**Comment by chansc2016** [comment]
> I'm not sure it's related to these 3 lines
> 
> ```
>     let message = new Message(msg) // <-- change these 3 lines
>     message.sender = senderId;   // fix
>     message.sender_id = senderId;  // fix
> ```
> 
> cause the crash relates to a `user` val, not a `message` or `senderId`
> 
> Could you please describe in more details this statement: "that the constructor having sender and sender_id as null".
> You mean `senderId` param of `onMessageListener` is null?

Hi, i can confirm it's totally related to this 3 line, because it's the same fix as the web version.

the original code:
onMessageListener(senderId, msg) {
    const message = new Message(msg)
   console.log(message);   // <--- your const message having message.sender_id is null because msg doesn't have a property of sender_id

<img width="1440" alt="Screenshot 2020-12-03 at 12 58 21 AM" src="https://user-images.githubusercontent.com/22651091/100905577-324ccc80-3503-11eb-92a3-3f22d6f100fc.png">

After that, the user that receive the message will become undefined at the message.js line 59 when you dispatch this message to the store.

message.js line 59
const user = otherSender ? store.getState().users[message.sender_id] : '.'   // <--- user is undefined because message.sender_id is null which will cause the above scenario i mention.

**Comment by DaveLomber** [comment]
Got it

so basically we need to apply a fix for React Native chat sample, 

here https://github.com/ConnectyCube/connectycube-reactnative-samples/blob/master/RNChat/src/services/chat-service.js#L179

and add one more line:

`message.sendder_id = senderId`

Correct?

**Comment by chansc2016** [comment]
Yes. just a simple fix for sample project.

**Comment by DaveLomber** [comment]
It's done 

https://github.com/ConnectyCube/connectycube-reactnative-samples/commit/69c67c4809d62a64941ff1207d9dc59a562cb775
