### ISSUE TITLE
chat.dialog.delete Not In expected result

### ISSUE THREAD

**Issue by kentplaza** [ConnectyCube/connectycube-js-sdk-releases#57]
For 1-1 private chat, after trigger chat.dialog.delete but dialog still appear in  Chat Dialogs list.

**Comment by DaveLomber** [comment]
The following rules are applied: 

- It's deleted for current user (User1)
- But for other user (User2) in this dialog - it's still will be there 
- Also, if User2 sends a new message - the dialog will be restored for User1

**Comment by kentplaza** [comment]
Thanks for explain. 
So if there any function in SDK that can total remove particular dialog as in admin.connectycube.com?
By the way, i tried add admin_ids when creating the dialog in order to delete by admin but seem like private chat will ignore admin_ids.

**Comment by DaveLomber** [comment]
Unfortunately there is no out of the box way to do so.

This might be provided in some near future 

A possible workaround as for now:
1) for a group chat, you can have a `system` user, which will be a part of each dialog as admin.
If need to remove a dialog - this user can remove other regular users and then remove itself.
Once all users left the group dialog - it will be destroyed .  
2) for 1-1 - there is no such a way to do so.
But you can use group dialogs for 1-1 chat as well and then the above solution will work

**Comment by kentplaza** [comment]
> Unfortunately there is no out of the box way to do so.
> 
> This might be provided in some near future
> 
> A possible workaround as for now:
> 
> 1. for a group chat, you can have a `system` user, which will be a part of each dialog as admin.
>    If need to remove a dialog - this user can remove other regular users and then remove itself.
>    Once all users left the group dialog - it will be destroyed .
> 2. for 1-1 - there is no such a way to do so.
>    But you can use group dialogs for 1-1 chat as well and then the above solution will work

Okay. You have the right term - "Destroy"
