### ISSUE TITLE
'Is typing' status work other way around

### ISSUE THREAD

**Issue by chansc2016** [ConnectyCube/connectycube-js-sdk-releases#58]
The document stated as `opponentId` but whenever i put as `opponentId` the listener doesn't return response. Instead if i use `currentUserId` the listener return response;

```
  const sendIsTyping = () => {
    ConnectyCube.chat.sendIsTypingStatus(ConnectyCube.service.currentUserId);
  };
```

<img width="1354" alt="Screenshot 2020-12-02 at 4 10 40 PM" src="https://user-images.githubusercontent.com/22651091/100846118-18869780-34b9-11eb-8869-8b1cb11a75c5.png">

**Comment by DaveLomber** [comment]
It's either opponent's `userId` if this is 1-1 chat or `dialogJid` if it's a group chat.

You basically should provide whom you want to notify about your typing. Hence `currentUserId` is a wrong value here.
