### ISSUE TITLE
Missing dialogId in onMessageTypingListener for Private Dialog

### ISSUE THREAD

**Issue by kentplaza** [ConnectyCube/connectycube-js-sdk-releases#59]
I got the dialogId is null result as below for the IsTyping Listerner SDK.
[ConnectyCube.chat.onMessageTypingListener] callback: true 276894 null

const onMessageTypingListener = (isTyping, userId, dialogId) => {
    console.log(
      '[ConnectyCube.chat.onMessageTypingListener] callback:',
      isTyping,
      userId,
      dialogId,
    );

For groupchat is fine, dialogId and userId return as expected

**Comment by DaveLomber** [comment]
This is expected behaviour for 1-1 

What I can suggest is to have some hash variable with opponentId -> dialogId and then look into it to get a dialogId for participantID
