### ISSUE TITLE
message.list always set to 100

### ISSUE THREAD

**Issue by chansc2016** [ConnectyCube/connectycube-js-sdk-releases#60]
Hi, although i set the limit to 1000 but the limit is forever 100.

const params = {
    chat_dialog_id: group_Id,
    sort_asc: 'date_sent',
    limit: 1000,
    skip: 0,
  };
![Screenshot 2020-12-07 at 5 20 51 PM](https://user-images.githubusercontent.com/22651091/101333374-7cda9a00-38b1-11eb-9d0b-07f1a12f5638.png)

const messages = await ConnectyCube.chat.message.list(params);
console.log(messages);

sdk version: 3.7.7

**Comment by ccvlad** [comment]
Hi, @chansc2016 
100 messages for one request is a maximum.
