### ISSUE TITLE
ConnectyCube.chat.muc.join return nothing

### ISSUE THREAD

**Issue by kentplaza** [ConnectyCube/connectycube-js-sdk-releases#62]
ConnectyCube.chat.muc.join return nothing after successfully join-in the dialog.
I tried using .then  and await to capture response but I only able to get nothing 
If error, .catch promise nicely fire.

**Comment by ccvlad** [comment]
Hi @kentplaza 
Yes, it's expected behavior. You should use `.then(() => {...})` if you want to do something after join to a dialog or use `.catch(error => {...})` to handle an error.
