### ISSUE TITLE
Sometimes receive duplicate push notifications `You have xxx new messages`

### ISSUE THREAD

**Issue by selfcreator** [ConnectyCube/connectycube-js-sdk-releases#65]
Not always, but sometimes receive duplicate push notifications `You have xxx new messages`, xxx is the same number like 3 4 5 etc.

The real message like `sender: content` is not duplicated, so I think it's a connectycube's bug since `You have xxx new messages` is a configuration on connectycube's dashboard, not controllable in the client code.

**Comment by DaveLomber** [comment]
Hi @selfcreator 
thank you for reporting the case 
we will investigate it on our end and let you know

**Comment by selfcreator** [comment]
@DaveLomber any update on this?

**Comment by joy-mollick** [comment]
> @DaveLomber

Don't worry , they will investigate more years later ,there are so many bugs with this sdk , and current many packages are not compatible with this .

**Comment by DaveLomber** [comment]
@joy-mollick 

" and current many packages are not compatible with this ."

Could you elaborate more here? What exact packages are not compatible?
I hear this for the 1st time

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
