### ISSUE TITLE
Not receiving push notifincation while app in

### ISSUE THREAD

**Issue by anand-esoft** [ConnectyCube/connectycube-js-sdk-releases#66]
Hello,

I am using Javascript SDK for connectycube. In that while calling from web to mobile device and app is terminated, call is not coming through in mobile devices.

While debugging the issue, we found that mobile devices expect push notifications for receiving calls which they didn't get when the app is terminated.

So, Can you please help what we need to do in this case?

**Comment by ccvlad** [comment]
Could you describe your expectation more detailed?
Do you use React Native or Cordova for mobile?
Is the app in background or in foreground?
Are going to get and accept the call?

**Comment by anand-esoft** [comment]
@ccvlad I am talking about Connectycube Javascript SDK for web. And calling from web to mobile device(Android/iOS). I can get and accept/reject call

**Comment by ccvlad** [comment]
@anand-esoft 

Try to configure and use the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API). Receive a notification and go to page with an incoming call.

We don't support push notification for a browser
