### ISSUE TITLE
How to restrict user to login into one browser only?

### ISSUE THREAD

**Issue by pooja-9spl** [ConnectyCube/connectycube-js-sdk-releases#68]
I have logged in with my user credentials in mozila firefox first, then I have loggedin in chrome browser. Then from mobile app I have sent message, I am not receiving messages in both browsers.

In that case, how to restrict user to prevent login if he/she is already logged to any other browser or device?

**Comment by DaveLomber** [comment]
ConnectyCube supports messages carbons, so when a user:

- online on 3 devices
- and sends a message from Device1
- then other 2 devices  will receive a message as well via `onMessageListener`

https://developers.connectycube.com/js/messaging?id=sendreceive-chat-messages

does it work at your end?

**Comment by pooja-9spl** [comment]
Yes, it is, but isn't there any way to end previous sessions when we logged in with any new device and create new session?

**Comment by DaveLomber** [comment]
@pooja-9spl it's normally expected to have multiple devices per user

Do you have a requirement to have only single device per user ?

**Comment by ccvlad** [comment]
Closed due inactivity, please re-open if the issue is still persists.
