### ISSUE TITLE
422 https://api.connectycube.com/login

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-js-sdk-releases#69]
Hi,

I'm getting `422 Unprocessable Entity`, with the message: `{
    "errors": {
        "password": [
            "cannot be blank"
        ]
    }
}` by making a POST to https://api.connectycube.com/login
The headers containes CB-token equal to what I've got POST https://api.connectycube.com/session, which worked fine, and in body { "login": my jwt token }

I followed the _[custom identity provider guide](https://developers.connectycube.com/guides/custom-identity-provider)_ but there nothing about a password!

What can I do?

**Comment by DaveLomber** [comment]
@dozsolti try to pass any random value in password , just to pass the validation

**Comment by DaveLomber** [comment]
Let's continue the discussion there https://github.com/ConnectyCube/connectycube-web-samples/issues/77
