### ISSUE TITLE
Extra param issues - multiple sessions for user

### ISSUE THREAD

**Issue by stepic-reply** [ConnectyCube/connectycube-js-sdk-releases#7]
If user A is logged on two different browsers (b1, b2) and user B calls user A, when user A accepts the call on browser b1, the javascript library (v.2.1.0) on browser b2 throws the following error:

TypeError: stanza is undefined                                cubeChatInternalUtils.js:89
    getElementText cubeChatInternalUtils.js:89
    _onSystemMessageListener cubeChat.js:750
    callbackStanza cubeChat.js:166
    apply self-hosted:1910
    emit events.js:134
    _onElement index.js:114
    _onElement self-hosted:882
    apply self-hosted:1910
    emit events.js:134
    onEndElement FramedParser.js:39
    onEndElement self-hosted:882
    apply self-hosted:1910
    emit events.js:134
    _handleTagOpening ltx.js:42
    write ltx.js:212
    write Parser.js:75
    _onData index.js:58
    _onData self-hosted:882
    apply self-hosted:1910
    emit events.js:134
    message Socket.js:33

Apparently the received stanza object is something like:

<message>
  <sent>
    <forwarded>
      <message>
        <extraParams>...</extraParams>
      </message>
    </forwarded>
  </sent>
</message>

And the _onSystemMessageListener function assumes that the <extraParams> element is inside the root <message> element.

Can you please help?
Thank in advance.

**Comment by ccvlad** [comment]
Thanks for the report. We've already check it. The issue related to the xml parser, it can't parse forwarded signalling message from the same user. We will fix our SDK and let you know about update.

**Comment by stepic-reply** [comment]
Hello, there are any updates about this? It's pretty critical.
Thank you.

**Comment by DaveLomber** [comment]
Hey @stepic-reply 
we will release it during next 1-2 days 
will post the update here 
thanks

**Comment by ccvlad** [comment]
Hi, @stepic-reply 
Check with our [latest SDK release (v2.1.6)](https://github.com/ConnectyCube/connectycube-js-sdk-releases/releases/tag/2.1.6).
