### ISSUE TITLE
SASLError: not-authorized on Custom identity authentication

### ISSUE THREAD

**Issue by Talented-Business** [ConnectyCube/connectycube-js-sdk-releases#70]
Hello
I am using custom identity authentication.
I am working on localhost, and I am modifying https://github.com/ConnectyCube/connectycube-web-samples/tree/master/chat.
I changed only both appCofig.json and services/auth-service.js.

```
  async connect(userId) {
    const token = ConnectyCube.service.sdkInstance.session.token;
    await ConnectyCube.chat.connect({ userId, password:token })
  }
```

When I am connecting chat, I have following errors.

```
[Chat] RECV: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>
cubeInternalUtils.js:115 [Chat] ERROR: SASLError: not-authorized
    at Function.fromElement (http://localhost:3001/static/js/0.chunk.js:13266:19)
    at Client.handler (http://localhost:3001/static/js/0.chunk.js:14687:26)
    at Client.emit (http://localhost:3001/static/js/0.chunk.js:31533:5)
    at Client._onElement (http://localhost:3001/static/js/0.chunk.js:12843:10)
    at FramedParser.emit (http://localhost:3001/static/js/0.chunk.js:31533:5)
    at FramedParser.onEndElement (http://localhost:3001/static/js/0.chunk.js:14998:12)
    at SaxLtx.emit (http://localhost:3001/static/js/0.chunk.js:31533:5)
    at SaxLtx._handleTagOpening (http://localhost:3001/static/js/0.chunk.js:37443:12)
    at SaxLtx.write (http://localhost:3001/static/js/0.chunk.js:37613:20)
    at FramedParser.write (http://localhost:3001/static/js/0.chunk.js:15302:17)
    at Client._onData (http://localhost:3001/static/js/0.chunk.js:12785:17)
    at Socket.emit (http://localhost:3001/static/js/0.chunk.js:31533:5)
    at WebSocket.listeners.message (http://localhost:3001/static/js/0.chunk.js:15050:16)
```

Can you help me?
What is wrong?

**Comment by DaveLomber** [comment]
@Talented-Business could you please post the complete flow , from the point where you create ConnectyCube session / login till the chat connect

**Comment by Talented-Business** [comment]
Do you mean source code?
I am using  https://github.com/ConnectyCube/connectycube-web-samples/tree/master/chat.
This is auth-service.js I modified.

import ConnectyCube from 'connectycube'
import appConfig from '../appConfig.json'
import User from '../models/user'
import store from '../store'
import { setCurrentUser } from '../actions/currentUser'
import { getImageLinkFromUID } from '../helpers/file'
import { LogOut } from '../reducers/index'

class AuthService {
  static CURRENT_USER_SESSION_KEY = 'CURRENT_USER_SESSION_KEY'
  static DEVICE_TOKEN_KEY = 'DEVICE_TOKEN_KEY'

  async init() {
    await ConnectyCube.init(...appConfig.connectyCubeConfig)
    return this.autologin()
  }

  async autologin() {
    const checkUserSessionFromStore = await this.getUserSession()
    if (checkUserSessionFromStore) {
      const data = JSON.parse(checkUserSessionFromStore)
      await this.signIn({ login: data.login, password: data.password })
      return 'home'
    } else { return 'auth' }
  }

  async signIn(params) {
    const session = await ConnectyCube.createSession(params)
    session.user = {
      id:session.id
    }
    const currentUser = new User(session.user)
    session.user.avatar = null;
    // work around
    session.user.full_name = `${session.user_id}`
    store.dispatch(setCurrentUser(session))
    const customSession = Object.assign({}, currentUser, { password: params.password, login:params.login })
    this.setUserSession(customSession)
    this.connect(customSession.id, session.token)
  }

  async signUp(params) {
    await ConnectyCube.createSession()
    await ConnectyCube.users.signup(params)
    return this.signIn(params)
  }

  async connect(userId) {
    const token = ConnectyCube.service.sdkInstance.session.token;
    console.log(token)
    await ConnectyCube.chat.connect({ userId, password:token })
  }

  setUserSession(userSession) {
    return localStorage.setItem(AuthService.CURRENT_USER_SESSION_KEY, JSON.stringify(userSession))
  }

  getUserSession() {
    return localStorage.getItem(AuthService.CURRENT_USER_SESSION_KEY)
  }

  async logout() {
    localStorage.clear()
    await ConnectyCube.logout()
    store.dispatch(LogOut())
  }


}

const authService = new AuthService()

Object.freeze(authService)

export default authService

**Comment by DaveLomber** [comment]
@Talented-Business thnaks
please also provided your custom identity provider settings in admin panel .

**Comment by Talented-Business** [comment]
api url:https://dev.fitemos.com/api/chat/verify-local
request params:{"id": "#{login}", "token": "#{password}"}
response params:{"uid": "#{user.id}","external_user_id":"#{user.id}"}
I think they are right.
When I enter wrong password, it doesn't login.

**Comment by DaveLomber** [comment]
@Talented-Business thanks, 
basically it should work well

but I guess I found the reason:

1) please remove this

```
 session.user = {
      id:session.id
    }
```

2) and then replace this line to 

```
 this.connect(customSession.user.id, session.token)
 ```

The `user` should be already in a `session` object

**Comment by Talented-Business** [comment]
yes it is working now.
But the session doesn't return user.
It is related with customSession.id.

**Comment by DaveLomber** [comment]
Glad it works

also, you can use another create session flow, in 2 steps:
- create empty session
- perform user login

It may work better in your case 

```
async signIn(params) {
    const session = await ConnectyCube.createSession()

    const user = await ConnectyCube.login(params)
    session.user = user
    session.user_id = user.id
    
    const currentUser = new User(session.user)
    session.user.avatar = getImageLinkFromUID(session.user.avatar)
    // work around
    session.user.full_name = session.user.login
    store.dispatch(setCurrentUser(session))
    const customSession = Object.assign({}, currentUser, { password: params.password })
    this.setUserSession(customSession)
    this.connect(customSession.id, customSession.password)
  }
 ```
