### ISSUE TITLE
React-Native Expo - App not starting after running `npm install react-native-connectycube --save`

### ISSUE THREAD

**Issue by Aurangempire** [ConnectyCube/connectycube-js-sdk-releases#71]
### React-Native Expo - App not starting after running :

`npm install react-native-connectycube --save`

Showing error: see screenshots:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-09 at 10 48 24](https://user-images.githubusercontent.com/77672040/110422473-741e7d80-80c5-11eb-9480-3cbd0589f4b8.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-09 at 10 51 39](https://user-images.githubusercontent.com/77672040/110422479-77b20480-80c5-11eb-8b7b-c89680744f41.png)

**Comment by ccvlad** [comment]
@Aurangempire 
1. `expo init expo-cc`
2. `cd expo-cc`
3. `npm install`
4. `npm install react-native-connectycube --save`
5.  In App.js: `import ConnectyCube from "react-native-connectycube"`
6. `npm run ios`

I haven't met the issue. See the screenshot below:
<img width="1680" alt="Screen Shot 2021-03-15 at 14 54 17" src="https://user-images.githubusercontent.com/43810932/111156376-573eea00-859e-11eb-9c76-da876963f688.png">
