### ISSUE TITLE
When I upgrade connectycube package from "2.1.0" to "3.7.8", it generates error.

### ISSUE THREAD

**Issue by Talented-Business** [ConnectyCube/connectycube-js-sdk-releases#72]
I changed connectycube package package.json on https://github.com/ConnectyCube/connectycube-web-samples/tree/master/chat.
And I used 3.7.8 version on my project.
They generate same errors.

./node_modules/connectycube/lib/videocalling_conference/cubeConferenceClient.js
SyntaxError: /home/topdev/web/connectycube-web-samples/chat/node_modules/connectycube/lib/videocalling_conference/cubeConferenceClient.js: Support for the experimental syntax 'classProperties' isn't currently enabled (12:22):

  10 |   }
  11 | 
> 12 |   DEVICE_INPUT_TYPES = DEVICE_INPUT_TYPES
     |                      ^
  13 |   CALL_TYPES = CALL_TYPES
  14 | 
  15 |   sessionsStore = {}

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.

**Comment by DaveLomber** [comment]
@Talented-Business can you try to add '@babel/plugin-proposal-class-properties' ?

**Comment by Talented-Business** [comment]
yes
But same error

**Comment by DaveLomber** [comment]
@Talented-Business  hmm, it should help..

can you please show your package-lock.json file

**Comment by Talented-Business** [comment]
{
  "name": "chat",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    ***@***.***/fontawesome-svg-core": "^1.2.27",
    ***@***.***/free-solid-svg-icons": "^5.12.1",
    ***@***.***/react-fontawesome": "^0.1.8",
    ***@***.***/jest-dom": "^4.2.4",
    ***@***.***/react": "^9.3.2",
    ***@***.***/user-event": "^7.1.2",
    "bootstrap": "^4.4.1",
    "connectycube": "^3.7.8",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-easy-crop": "^2.1.0",
    "react-modal": "^3.11.2",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.3.1",
    "react-transition-group": "^4.3.0",
    "recyclerlistview": "^3.0.0",
    "redux": "^4.0.5",
    "sweetalert": "^2.1.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by banshiAnton** [comment]
HI @Talented-Business try to import .min.js
```javascript
import ConnectyCube from “../../node_modules/connectycube/dist/connectycube.min.js”
```

**Comment by Talented-Business** [comment]
yes it is working.
So what is wrong?

**Comment by banshiAnton** [comment]
this JS feature currently is not supported (Class fields)
