### ISSUE TITLE
onMessageListener doesn't listen when I update message text or delete message.

### ISSUE THREAD

**Issue by Talented-Business** [ConnectyCube/connectycube-js-sdk-releases#73]
I implemented updating message text and deleting message using ConnectyCube.chat.message.update and ConnectyCube.chat.message.delete.
But whenever updating and deleting message, I can't change other user chat body as real time.
What listener can I use for them?

**Comment by DaveLomber** [comment]
We recommend using the following API:

EDIT:

```
ConnectyCube.chat.editMessage({
  to: 123, // 52e6a9c8a18f3a3ea6001f18
  dialogId: "52e6a9c8a18f3a3ea6001f18",
  body: "corrected message body",
  originMessageId: "58e6a9c8a1834a3ea6001f15",
  last: false
})

...

ConnectyCube.chat.onMessageUpdateListener = (messageId, isLast, updatedBody, dialogId, userId) {

}
```

DELETE:

```
ConnectyCube.chat.deleteMessage({
  to: 123, // 52e6a9c8a18f3a3ea6001f18
  dialogId: "52e6a9c8a18f3a3ea6001f18",
  messageId: "58e6a9c8a1834a3ea6001f15"
})

...

ConnectyCube.chat.onMessageDeleteListener = (messageId, dialogId, userId) {

}

```

This API will be released to public in 2 days

**Comment by ccvlad** [comment]
Hello, @Talented-Business 
Please check the SDK version 3.8.0

**Comment by DaveLomber** [comment]
@Talented-Business this is documentation 

https://developers.connectycube.com/js/messaging?id=edit-message

https://developers.connectycube.com/js/messaging?id=delete-messages
