### ISSUE TITLE
Video: Can't accept the call, there is no information about peer connection by some reason.

### ISSUE THREAD

**Issue by shawnlauzon** [ConnectyCube/connectycube-js-sdk-releases#74]
I'm trying to do a video call with another person. Both streams seem to be setup well, but when I call `session.call({})`, and from the `onCallListener` from the other browser (which I received {`bandwidth: "0"}` as the extension), I then call `session.accept({})`. This is displayed in the JS console:

`[VideoChat]: – "Can't accept the call, there is no information about peer connection by some reason."`

I don't see anything else suspicious in the console. And I'm just getting started with using ConnectyCube, so this might be a problem on my side. 

Using connectycube javascript SDK v3.8.0

**Comment by shawnlauzon** [comment]
Not sure the reason for this, but when I run the sample web code everything works well. So I'm going to backport from that.

**Comment by ccvlad** [comment]
Hi @shawnlauzon !
Please attach logs from receiver and sender. We will check to find the issue.

**Comment by Abdelrahman-Nabil** [comment]
I have the same issue, it started showing this error all of a sudden.
did you figure out a real solution to this ?

**Comment by bennetlee** [comment]
Hi, may I know if you all managed to solve this? I am experiencing the same issue...:( Thanks!
