### ISSUE TITLE
React/Nextjs: Webpack can't parse ConnectyCube NPM module 

### ISSUE THREAD

**Issue by shawnlauzon** [ConnectyCube/connectycube-js-sdk-releases#75]
I'm trying to use ConnectyCube in a React+Nextjs project. I'm loading ConnectyCube 3.9.1 via npm, and when I do this call:

`ConnectyCube.init(credentials, appConfig);`

This error occurs from webpack:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/611529/115717209-25425400-a3a4-11eb-98e0-6bf5d5215ac0.png">

I looked at this part of ConnectyCube, and the code doesn't make sense to me. Is there some pre-processing that is supposed to be done, and webpack should be somehow be told to skip it? Is using NPM to load ConnectyCube on a React project not allowed?

```
class ConferenceClient {
...

  DEVICE_INPUT_TYPES = DEVICE_INPUT_TYPES
  CALL_TYPES = CALL_TYPES

  sessionsStore = {}

  onParticipantJoinedListener
  onParticipantLeftListener

  onSlowLinkListener
  onRemoteStreamListener
  onRemoteConnectionStateChangedListener
  onSessionConnectionStateChangedListener

  createNewSession() {
...
```

**Comment by ccvlad** [comment]
Hi, @shawnlauzon 
Please check this comment - https://github.com/ConnectyCube/connectycube-js-sdk-releases/issues/72#issuecomment-799309914

**Comment by shawnlauzon** [comment]
Fantastic, that worked brilliantly. Thank you!
