### ISSUE TITLE
ConnectyCube.pushnotifications.subscriptions.create return 401 error 

### ISSUE THREAD

**Issue by pratham014** [ConnectyCube/connectycube-js-sdk-releases#76]
I am getting error '401 Token is required' when trying to subscribe to push notification service with ConnectyCube.pushnotifications.subscriptions.create API even though I am passing the token details. 

Environment Details:-
React Native :- 0.63.4
react-native-connectycube : - 3.7.8

Parameters passed to the API :-
{
	"notification_channels": "gcm",
	"device": {
		"platform": "android",
		"udid": "34a1d193a40a316d"
	},
	"push_token": {
		"environment": "development",
		"client_identification_sequence": "cQeR8ZCLT9WreV95em05-v:APA91bE7hXGQBsYtf2obd8NbQEf9c3Y-0z0bhhP5FcmaXA4_Z3AgiLPzw0AUJ5RB2yjhD7ihTR2Y83heGxIEUd6nd-NO3mZbEdjWIo1omzuS7HR9_MWM43ViuNTpxjemT7sYYGbHZkuP",
		"bundle_identifier": "com.josei"
	}
}

Response Received:- 

{
	"code": 401,
	"info": {
		"errors": ["Token is required"]
	}
}

Invocation Code :-
subcribeToPushNotification(token) {
    console.log('Notification toke >>>>>>>>>>>>>>>>>>>>>>>', token);
    //alert("token "+token.token)
    const DeviceInfo = require('react-native-device-info').default;
    const params = {
      notification_channels: Platform.OS === 'ios' ? 'apns' : 'gcm',
      device: {
        platform: Platform.OS,
        udid: DeviceInfo.getUniqueId(),
      },
      push_token: {
        environment: __DEV__ ? 'development' : 'production',
        client_identification_sequence: token.token,
        bundle_identifier : "com.josei"
      },
    };
    console.log("PushNotificationService params ", params)
    ConnectyCube.pushnotifications.subscriptions
      .create(params)
      .then((result) => {
        alert('PushNotificationService - result', result);
        AsyncStorage.setItem(
          PushNotificationService.DEVICE_SUBSCRIPTION_ID,
          `${result[0].subscription.id}`,
        );
      })
      .catch((error) => {
        console.log('PushNotificationService - param', JSON.stringify(params));
        console.log('PushNotificationService - error', JSON.stringify(error));
      });
  }

**Comment by ccvlad** [comment]
Hi, @pratham014 
Please check the doc - https://developers.connectycube.com/js/authentication-and-users?id=create-session-token
You haven't create a session to use API calls

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
