### ISSUE TITLE
No more spaces in group names, but why?

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-js-sdk-releases#77]
Hi,

From the recent update you cannot use spaces in a group's name.

But I don't understand why?

![image](https://user-images.githubusercontent.com/17215747/117125135-d2a06900-ada1-11eb-9777-447148727fd5.png)

**Comment by DaveLomber** [comment]
@dozsolti can you check now?

**Comment by dozsolti** [comment]
Works, thank you!
