### ISSUE TITLE
newOccupantsIds.filter is not a function - Dashboard

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-js-sdk-releases#78]
Tried to add a new occupant into a group chat and got this

![image](https://user-images.githubusercontent.com/17215747/117254481-1dc58500-ae51-11eb-9040-06615a1cf897.png)

**Comment by DaveLomber** [comment]
we have deployed the patch

Could you please check at your side and let us know whether the issue is resolved

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
