### ISSUE TITLE
this.dialog.occupants_ids.push is not a function - Dashboard

### ISSUE THREAD

**Issue by dozsolti** [ConnectyCube/connectycube-js-sdk-releases#79]
Hi,

Two issues:
1.) I went to edit a dialog by id, changed nothing and pressed saved=> The occupants ids was clear 
2.) When I went to add them back this error occured

![image](https://user-images.githubusercontent.com/17215747/117259837-1c975680-ae57-11eb-8ff3-d4c0038f4728.png)

**Comment by DaveLomber** [comment]
we have deployed the patch

Could you please check at your side and let us know whether the issue is resolved

**Comment by dozsolti** [comment]
@DaveLomber The same even after a Hard reload

**Comment by banshiAnton** [comment]
Hi @dozsolti can you please check now

**Comment by dozsolti** [comment]
Worked, thanks
