### ISSUE TITLE
Couldn't find user 

### ISSUE THREAD

**Issue by CMLCNL** [ConnectyCube/connectycube-js-sdk-releases#8]
```

ConnectyCube.createSession({ login: "tele***", password: "****" })
  .then(session => {
    console.log(session);
  }).catch(error => { 
    console.log(error);
  });

  let model = {
     id: parseInt(userId),
     full_name: "baris"
  }
   
   try {
      let data = await ConnectyCube.users.update(model);
```

we cant update any user name or any field.
we get error on server Couldn't find user. 
because connect cube js sdk take current user id 

what we happen?

**Comment by DaveLomber** [comment]
@CMLCNL  if you receive `Couldn't find user.` then it means you pass a wrong user id, especially this one: `parseInt(userId)`.

I recommend the following:

- double check a userId is a valid value and a user with this id is a real one 
- you can update only our own user 
- make sure you do it after session is created, e.g. this way:

 ```
ConnectyCube.createSession({ login: "tele***", password: "****" })
  .then(session => {
    console.log(session);

     let model = {
        id: parseInt(userId),
        full_name: "baris"
     }
   
     let data = await ConnectyCube.users.update(model);

  }).catch(error => { 
    console.log(error);
  });
```
