### ISSUE TITLE
Retrieve users by ID not worked.

### ISSUE THREAD

**Issue by tommychen1228** [ConnectyCube/connectycube-js-sdk-releases#80]
I used the method 
`const params = {
  page: 1,
  per_page: 5,
  filter: {
    field: "id",
    param: "in",
    value: [userId],
  },
};

ConnectyCube.users
  .get(params)
  .then((result) => {})
  .catch((error) => {});`

It had worked well before. But now it does not work.

The below is sdk request and response.

`[Request][22] GET https://api.connectycube.com/users.json {"data": {"filter": ["string id in 3406199"], "page": 1, "per_page": 10}, "type": "GET", "url": "https://api.connectycube.com/users.json"}`
` [Response][22] {"current_page": 1, "items": [], "per_page": 0, "total_entries": 0}`

**Comment by DaveLomber** [comment]
@tommychen1228 could you make sure 'userId' is number and not a string

**Comment by tommychen1228** [comment]
I use parseInt(userId), then it works well.Thank you.

**Comment by DaveLomber** [comment]
Sweet, 

thank you for confirmation
