### ISSUE TITLE
Failed to login createSession with users's login that contain '+' symbol

### ISSUE THREAD

**Issue by soonzhi** [ConnectyCube/connectycube-js-sdk-releases#81]
const userCredentials = { login: "+60164421233", password: "password" };

ConnectyCube.createSession(userCredentials)
  .then((session) => {})
  .catch((error) => {});

when we trying to call this, it show regex error.

**Comment by DaveLomber** [comment]
This was fixed 1h ago

Could you please check again

**Comment by soonzhi** [comment]
ok fixed. checked
