### ISSUE TITLE
Cannot read property 'is_enabled' of null

### ISSUE THREAD

**Issue by zicodeng** [ConnectyCube/connectycube-js-sdk-releases#82]
Not sure what's going on, it has been working fine until recently I am seeing this error with new users...

```
// Use chat application session token sent from server to initialize
CB.init({
  appId: CB_APP_ID,
  token,
});

// Because we are using custom identity authentication
// the current user's session token is used as password
const password = getSessionToken();
if (!password) {
  throw new Error(ChatServiceError.MissingUserSessionToken);
}

// Upgrade chat application session to user session
// https://developers.connectycube.com/js/authentication-and-users?id=upgrade-session-token-user-login
const chatUser = await CB.login({
  login: userId,
  password,
});
this.currentChatUser = chatUser;
```

Custom identity provider setting:
![image](https://user-images.githubusercontent.com/24593509/117610832-3d8dcf00-b117-11eb-8e02-68ae86a15b98.png)

When a new user is created via `CB.login` (can confirm that a new user appears in ConnectyCube dash), I am getting this error: `Cannot read property 'is_enabled' of null`, not sure what `is_enabled` here means 🤔 

Any help would be appreciated! Thanks!

**Comment by DaveLomber** [comment]
Are you getting this error when call CB.login? Could you share the complete error response message

**Comment by zicodeng** [comment]
@DaveLomber Yes!

![image](https://user-images.githubusercontent.com/24593509/117613616-0372fc00-b11c-11eb-8e87-0e25c0335c71.png)

**Comment by DaveLomber** [comment]
It seems it's related to user confirmation email 

Could you try to do the following workaround:
- go to admin panel, users, email notifications 
- tick checkbox for 'ENABLE 'EMAIL CONFIRMATION' EMAIL WHEN USER SIGNS UP' and click save 
- untick checkbox for 'ENABLE 'EMAIL CONFIRMATION' EMAIL WHEN USER SIGNS UP' and click save 

then try again the login API  - will it work now?

**Comment by zicodeng** [comment]
@DaveLomber Looks like a 🐛 to me? It is working now, but I didn't do anything 🤷‍♀️

Thanks for your help!
