### ISSUE TITLE
 wss://chat.connectycube.com connection error

### ISSUE THREAD

**Issue by miralayipouya** [ConnectyCube/connectycube-js-sdk-releases#83]
Hi! today i am facing connectivity problem initializing the chat:

![cube-error](https://user-images.githubusercontent.com/81193445/118399736-d40c4400-b673-11eb-91b6-b5ffde046473.png)

js sdk: 3.9.2

**Comment by DaveLomber** [comment]
@ccvlad can you check ?

**Comment by ccvlad** [comment]
Didn't get the error. This is normal behavior if chat tries do reconnect after was disconnected not by user (`ConnectyCube.chat.disconnect()` wasn't called)

@miralayipouya, is the error still reproduce for you?

**Comment by miralayipouya** [comment]
@ccvlad i am not facing this issue anymore, but at the time i was, i noticed it is my ip geolocation (IRAN) which is causing this issue.

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
