### ISSUE TITLE
Firebase Authentication via phone number, Error ["Both user login and email can't be blank"]

### ISSUE THREAD

**Issue by spectrox0** [ConnectyCube/connectycube-js-sdk-releases#84]
When trying to login with the phone number following the documentation , I get error ["Both user login and email can't be blank"]

**Comment by DaveLomber** [comment]
@spectrox0 thank you for reporting the case
The team is checking the underlying API 
Will let you know soon

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
