### ISSUE TITLE
Updating occupant_ids error

### ISSUE THREAD

**Issue by iberatkaya** [ConnectyCube/connectycube-js-sdk-releases#86]
I have a 'group' chat dialog. Previously a user could leave the dialog without any problems. Now when a user tries to leave it, ConnectyCube throws an error with a code 403 stating that "Updating occupant_ids is possible only for 'group' and 'public' chat dialogs". I have not made any changes to the code, so I am not sure what has changed. I am certain that all my dialogs are of type 'group':

<img width="450" alt="image" src="https://user-images.githubusercontent.com/34488374/119572690-d2512780-bdbb-11eb-8ab3-6543371c20e2.png">

**Comment by DaveLomber** [comment]
@iberatkaya could you share the dialog id where you have an issue?

**Comment by iberatkaya** [comment]
I have this issue only when an occupant tries to leave a dialog and it occurs currently on every dialog. Here is an example dialog with an id "60ae568832c0940011e8bcba". The user with id "4282398" has created a "group" (type 2) dialog. When the user with id "2836873" tries to remove themselves from the dialog, CC throws the following error: "Updating occupants_ids is possible only for 'group' and 'public' chat dialogs". I am using the JavaScript SDK.

The dialog:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/34488374/119675375-a67a8400-be45-11eb-9011-1c7807090fe7.png">

**Comment by DaveLomber** [comment]
@iberatkaya thanks, will check it

**Comment by DaveLomber** [comment]
Can you check now?

**Comment by iberatkaya** [comment]
Yes, the issue seems to be resolved. Thank you!
