### ISSUE TITLE
Url Attached Files on Message are not legible

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-js-sdk-releases#88]
I have this fragment to receive files:

```
ConnectyCube.chat.onMessageListener = onMessage;

function onMessage(userId, message) {
            console.log('[ConnectyCube.chat.onMessageListener] callback:', userId, message);
            var dv_message = $('#dv_mensajeschat');

            if (message.extension.hasOwnProperty('attachments')) {
                if (message.extension.attachments.length > 0) {
                    const fileUID = message.extension.attachments[0].uid;
                    const fileUrl = ConnectyCube.storage.privateUrl(fileUID);
                    const type = message.extension.attachments[0].type;
                    if (type == 'image') {
                        dv_message.append('<div style="margin:2px;padding:2px;background-color:#EFF7FA;"><b>Paciente:</b><br><div style="text-align:center;"><a href="' + message.extension.attachments[0].url + '" target="_blank"><img src="' + message.extension.attachments[0].url + '" alt="photo" style="width:20%;height:20%"/></a></div></div>');
                    }

                    if (type == 'data') {
                        dv_message.append('<div style="margin:2px;padding:2px;background-color:#EFF7FA;"><b>Paciente:</b> <a href="' + message.extension.attachments[0].url + '" target="_blank">Ver Archivo</a></div>');
                    }
                    console.log('=>' + JSON.stringify(message.extension.attachments[0]));
                }
            } else {
                if (message.body) {
                    dv_message.append('<div style="margin:2px;padding:2px;background-color:#EFF7FA;"><b>Paciente:</b> ' + message.body + '</div>');
                }
            }
            dv_message.find('.msj_isTyping').remove();
            dv_message.scrollTop(dv_message[0].scrollHeight);
        }
```
The problem is that the urls that represent and image or pdf file does not allow to view the image or the pdf file in a new tab.

I am getting urls of this type: https://api.connectycube.com/blobs/D72F4375BE3613E70D5D2EA023605EB08E9D

How do I convert this url in a legible file to view it in a new tab in the browser?

![1](https://user-images.githubusercontent.com/3847133/119762069-a3e25380-be72-11eb-94a8-9d6dcca455ea.jpg)

**Comment by DaveLomber** [comment]
It allows either to download the file or you can show it inside HTML <img> element  

Are you looking for anything different?

**Comment by alxx28** [comment]
For Images works inside  HTML element, but for a PDF a I am doing this and does not work:

dv_message.append('<iframe src="'+message.extension.attachments[0].url+'" type="application/pdf" width="100%" height="100%" style="overflow: auto;"></iframe>');

This is the downloaded file:
![image](https://user-images.githubusercontent.com/3847133/119868486-b2695300-bee4-11eb-9879-901b3b2aa1d0.png)

And I have manually to put the extension "PDF" to be able to view it.

![image](https://user-images.githubusercontent.com/3847133/119868662-f197a400-bee4-11eb-88ac-6696d3397482.png)

The same thing occurs with the images.

**Comment by alxx28** [comment]
I solved it with this: [https://blog.jayway.com/2017/07/13/open-pdf-downloaded-api-javascript/](url), taking this solution I can open the PDF file in a new tab in the browser.
