### ISSUE TITLE
Blobs POST endpoint returning incorrect s3 url (blob_object_access)

### ISSUE THREAD

**Issue by ethanx94** [ConnectyCube/connectycube-js-sdk-releases#89]
Hello,
I've been having an inconsistency in the API response when uploading files. The response from the POST blobs/ endpoint returns an S3 url which has a content_type parameter as snake case. After these query parameters are parsed the POST to https://s3.amazonaws.com/cb-shared-s3 is called and files are instead stored as binary/octet-stream.

![image](https://user-images.githubusercontent.com/4449468/120498214-0f558500-c38d-11eb-9454-7adfbef7ca39.png)

![image](https://user-images.githubusercontent.com/4449468/120498419-3318cb00-c38d-11eb-883e-44451027e0c0.png)

![image](https://user-images.githubusercontent.com/4449468/120497874-c4d40880-c38c-11eb-8ded-9c168a95ce2d.png)

I believe the S3 API is looking for the Content-Type key, however trying to do this manually, I get a 412 error, possibly for an invalid signature.

Is there anything that can be fixed on the backend to accommodate this?

**Comment by banshiAnton** [comment]
Hi @ethanx94 we have deployed latest changes, so please check now

**Comment by ethanx94** [comment]
Perfect, works great again. Old stuff is kinda stuck in limbo (this is just test data so it doesn't matter much) but any new uploads do work as expected.
Thanks 👍
