### ISSUE TITLE
What is the old password of the user who has logged in with firebase phone?

### ISSUE THREAD

**Issue by CMLCNL** [ConnectyCube/connectycube-js-sdk-releases#9]
What is the password of the user who has logged in with firebase phone?

**Comment by DaveLomber** [comment]
@CMLCNL I guess you are talking about change password request 

If you use Firebase phone auth, then there is no a user's password and also you do not to use a password change functionality with ConnectCube API, cause you authorize a user by SMS code 

does it make sense?
