### ISSUE TITLE
Row-level permissions validation error for custom objects (open_for_users_ids)

### ISSUE THREAD

**Issue by ethanx94** [ConnectyCube/connectycube-js-sdk-releases#90]
Hello, I'm having a slight issue today with changing permissions on a custom object. Both from the admin panel as well as from the sdk I get a 422.
`Field ids should be an array`
Is there anything that can be fixed on the server side?

![image](https://user-images.githubusercontent.com/4449468/121080633-a796a400-c7a9-11eb-9211-e0f72aeb5eb5.png)
![image](https://user-images.githubusercontent.com/4449468/121080898-01976980-c7aa-11eb-93e7-b8b83b65e174.png)

**Comment by banshiAnton** [comment]
Hi @ethanx94 
in SDK try to use 'ids' and 'groups' fields
example https://developers.connectycube.com/server/custom_objects?id=parameters-1
NOT users_ids
change it to ids

**Comment by ethanx94** [comment]
That seems to work. I suppose the confusion is in the response object which contains users_ids. Anyway it does work now, thank you

![image](https://user-images.githubusercontent.com/4449468/121189382-0c98db00-c838-11eb-93fd-ef58dd651683.png)
