### ISSUE TITLE
Remote Stream does not work in chrome based browsers between Web App and Android Mobile App

### ISSUE THREAD

**Issue by alxx28** [ConnectyCube/connectycube-js-sdk-releases#91]
@DaveLomber
Hello, I have a web app(Medic) and an Android Mobile App(Patient), the problem is the following, when the video is started from mozilla the video calling works very well, but when the video calling  is started from  chrome based browsers the remote stream does not work.

**Chrome**
![chrome](https://user-images.githubusercontent.com/3847133/121392911-6fac6f80-c915-11eb-8289-f1a052918643.jpg)

**Mozilla**
![mozilla](https://user-images.githubusercontent.com/3847133/121392976-7d61f500-c915-11eb-8be5-9076992b0783.jpg)

Checking the console I see that in chrome the remote stream is not being assigned, I mean this fragment in the initiator is not executed:

```
ConnectyCube.videochat.onRemoteStreamListener = setStream;

function setStream(session, userID, remoteStream) {
            console.log('Remote Stream Assigned');
            session.attachMediaStream('vd_video2', remoteStream);
            $('#btn_mutesound').off('click').on('click', {x: session, y: 'unmute'}, setSound);
            $('#btn_unmutesound').off('click').on('click', {x: session, y: 'mute'}, setSound);
            $('#btn_mutevideo').off('click').on('click', {x: session, y: 'unmute'}, setVideo);
            $('#btn_unmutevideo').off('click').on('click', {x: session, y: 'mute'}, setVideo);
        }
```
But before last chrome updates this was working very well.
I also have the video calling between web apps and works very well, the problem is between the web and android mobile app.
Use version is 3.7.1.

Here a PDF file to check the web app and mobile apps.
[Web-Mobile.pdf](https://github.com/ConnectyCube/connectycube-js-sdk-releases/files/6625388/Web-Mobile.pdf)

Source Code Line 9957: https://www.cronhis.xyz/js/historia/consultaexterna/consultaexterna.js

**Comment by DaveLomber** [comment]
@alxx28 just to clarify - what platform you use on Android mobile? 
is it WEb / Cordova / RN ?

**Comment by DaveLomber** [comment]
On Chrome logs I do not see onAccept event by some reason 
That's the main  issue 

Does other party (mobile) sends it properly?

**Comment by ccvlad** [comment]
> Did you got any solutions?

@prashantJangidSys this issue is too old and the previous reporter didn't give feedback. If you have a question, please create a separate issue and add information there that will help us determine the cause (logs from caller and callee side, devices, framework, OS, ConnectyCube SDK version, steps to reproduce will be helpful).
