### ISSUE TITLE
Geeing issues in ios but it is working fine in ANDROID

### ISSUE THREAD

**Issue by LoknathPandit** [ConnectyCube/connectycube-js-sdk-releases#92]
Hi, I’m @LoknathPandit Getting this error in ios but it is working fine in android please suggest me asas what should i do in order to solve this issues, TypeError: null is not an object (evaluating '_reactNativeConnectycube.default.videochat.onCallListener = this._onCallListener')

**Comment by ccvlad** [comment]
Is it React Native, Cordova or browser?

**Comment by ccvlad** [comment]
Make sure that you assign listener after ConnectyCube.init() was called and you do not use Expo SDK (React Native WebRTC lib for videocalls does't work with Expo yet)

**Comment by LoknathPandit** [comment]
can you share link from where i can integrate it properly in ios

**Comment by LoknathPandit** [comment]
Please share a sample code i am trying to fix this bug from last 3days but no luck.

**Comment by ccvlad** [comment]
https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat

Our demo, please

**Comment by LoknathPandit** [comment]
solved it by changing react-native version
