### ISSUE TITLE
ld: library not found for -lDoubleConversion

### ISSUE THREAD

**Issue by LoknathPandit** [ConnectyCube/connectycube-js-sdk-releases#93]
Getting this issue in your repo code during archive 
And in my project getting this issue "ld: library not found for -lreact-native-webrtc" during archive

but both app  is working fine in debug mode in simulator so can you please help me.

**Comment by ccvlad** [comment]
Hi @LoknathPandit !
You haven't probably linked the react-native-webrtc lib with project. The lib is using to support video/audio calls (webrtc).
If you would like to have this functions, please follow the guide - https://developers.connectycube.com/reactnative/videocalling?id=connect-webrtc-lib

**Comment by ccvlad** [comment]
Please, describe your issue more detailed if I misunderstood you.
Attach full log. It may be helpful, besause I don't remember the same case on my practice. Thanks!

**Comment by LoknathPandit** [comment]
![simulator_screenshot_061A98F7-7ACD-4FA2-A8FC-187F81CE46D2](https://user-images.githubusercontent.com/45422600/123222448-96f66580-d4ed-11eb-800a-24f01b04d3c7.png)
<img width="1440" alt="Screenshot 2021-06-24 at 1 11 11 PM" src="https://user-images.githubusercontent.com/45422600/123222533-aaa1cc00-d4ed-11eb-80c1-de8aa56456af.png">

**Comment by LoknathPandit** [comment]
your repo code is working fine in debug mode i mean in simulator but when i am going to archive it then i am getting 
ld: library not found for -lDoubleConversion

**Comment by LoknathPandit** [comment]
also i have created one new project in which i am getting  "ld: library not found for -lreact-native-webrtc" issue
but both project is working fine in debug mode i mean in sumulator 
only getting issue during archive(Build release ipa)

**Comment by ccvlad** [comment]
Try next steps:
1. Product > Clean Build Folder (Xcode);
2. Remove `node_modules`;
3. Remove `ios/Podfile.lock`;
4. `npm install` from path where project's `package.json` is locating;
5. `cd ios && pod install &&  sh ../node_modules/react-native-webrtc/tools/downloadBitcode.sh`;
6. Set `Any iOS Device (arm64)`;
7. Product > Archive (Xcode).

**Comment by ccvlad** [comment]
I don't see option `Any iOS Device (armv7)`, only `Any iOS Device (arm64)` presents in Xcode.
Somehow you need to change `Any iOS Device (armv7)` >>> `Any iOS Device (arm64)`. Please see the issue - https://github.com/react-native-webrtc/react-native-webrtc/issues/1025

**Comment by LoknathPandit** [comment]
sir just getting message  Downloading Files with version number 1.89.3 but nothing happen still i am waitting from last 30 min

**Comment by ccvlad** [comment]
> I don't see the option `Any iOS Device (armv7)`, only `Any iOS Device (arm64)` presents in Xcode.
> Somehow you need to change `Any iOS Device (armv7)` >>> `Any iOS Device (arm64)`. Please see the issue - [react-native-webrtc/react-native-webrtc#1025](https://github.com/react-native-webrtc/react-native-webrtc/issues/1025)

This is main problem. So you should use the `Any iOS Device (arm64)` as scheme's  target.


> sir just getting message Downloading Files with version number 1.89.3 but nothing happen still i am waitting from last 30 min

I was thinking that download bitcode for iOS WedRTC would solve the issue, but it isn't. After `cd ios && sh ../node_modules/react-native-webrtc/tools/downloadBitcode.sh` it should download bitcode from assets (size 206Mb, https://github.com/react-native-webrtc/react-native-webrtc/releases/tag/1.89.3)

**Comment by LoknathPandit** [comment]
Thank you sir for  helping  solved issues
