### ISSUE TITLE
Cannot read property 'peerConnectionInit' of undefined

### ISSUE THREAD

**Issue by victormongi** [ConnectyCube/connectycube-js-sdk-releases#94]
Cannot read property 'peerConnectionInit' of undefined
How to solve this, thank you...
<img width="558" alt="Screen Shot 2021-07-02 at 9 10 20 AM" src="https://user-images.githubusercontent.com/5617746/124206156-54e4a980-db15-11eb-8c72-f213c243202e.png">

Call from web browser to react-native

    ConnectyCube.videochat._onCallListener = this._onCallListener;
    ConnectyCube.videochat._onAcceptListener = this._onAcceptCallListener;
    ConnectyCube.videochat._onRejectListener = this._onRejectCallListener;
    ConnectyCube.videochat._onStopListener = this._onStopCallListener;

I found that this is changed to in newer version

**Comment by ccvlad** [comment]
Hi @victormongi 

Do not overwrite internal listeners like `ConnectyCube.videochat._onCallListener` etc.
Please refer to our docs [Video Calling](https://developers.connectycube.com/js/videocalling).

**Comment by victormongi** [comment]
<img width="677" alt="Screen Shot 2021-07-05 at 8 25 30 AM" src="https://user-images.githubusercontent.com/5617746/124403781-928e4000-dd6a-11eb-9122-aeee355d2c7a.png">
I use this but this doesn't work, please help

**Comment by ccvlad** [comment]
I can't figure out what exactly isn't working. Could you show what is displayed in the log?

This code works in our [JS Videochat Sample](https://github.com/ConnectyCube/connectycube-web-samples/tree/master/videochat).

**Comment by victormongi** [comment]
Could you use this 
https://github.com/ConnectyCube/connectycube-reactnative-samples/tree/master/RNVideoChat
and try using the latest connectycube.

This is the error when I remove the underscore
![telegram-cloud-photo-size-5-6296193104570593546-y](https://user-images.githubusercontent.com/5617746/125227063-c0dcc400-e304-11eb-97ab-2821fc076c74.jpg)

**Comment by MuahammdUmar** [comment]
@victormongi  did you solve the issue. I am facing the same issue, could the react native version be the issue ?

**Comment by DaveLomber** [comment]
https://github.com/ConnectyCube/connectycube-reactnative-samples

New React Native code samples have been released, please give it a try
