### ISSUE TITLE
Remote Listener

### ISSUE THREAD

**Issue by HusseinY-DeV** [ConnectyCube/connectycube-js-sdk-releases#96]
ConnectyCube.videochatconference.onRemoteStreamListener = this.onRemoteStreamListener.bind(this);

 onRemoteStreamListener = (session, userId, stream) => {
    console.log("ABCDEFGHIJKLMNOP");
    CallService.processOnRemoteStreamListener(userId)
      .then(() => {
        this.updateRemoteStream(userId, stream);
        this.setOnCall();
      })
      .catch(this.hideInomingCallModal);
  };

**Comment by DaveLomber** [comment]
@HusseinY-DeV could you please specify what issue are you facing

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
