### ISSUE TITLE
onMessage listener is not always being triggered onMessage from the web app which is also using react connectycube chat

### ISSUE THREAD

**Issue by HusseinY-DeV** [ConnectyCube/connectycube-js-sdk-releases#97]
ConnectyCube.chat.onMessageListener = this.onMessageListener;
    onMessageListener = (senderId, msg) => {
        Alert.alert("LISTENED", JSON.stringify(senderId));
        store.dispatch({ type: "UPDATE_DIALOG", payload: msg });
    };

    setUpListeners() {
        ConnectyCube.chat.onMessageListener = this.onMessageListener;
        AppState.addEventListener('change', this.handleAppStateChange);
    }

i am calling setUpListeners on the didMount of the stack that will be holding all the dialogs and chats altho it doesnt seem to be triggered, it gets triggered sometimes when i disconnect programmatically the alerts appear

**Comment by DaveLomber** [comment]
Could you provide a snippet how you send a message from Web

**Comment by HusseinY-DeV** [comment]
> Could you provide a snippet how you send a message from Web

The message sent is from the connectycube chat web sample i changed nothing ,only the app config credentials so that i could connect to my connectycube app

**Comment by DaveLomber** [comment]
Ok then let's do the following

at RN side:

1 - enable logs 

```
const CONFIG = {
  debug: { mode: 1 }, // enable DEBUG mode (mode 0 is logs off, mode 1 -> console.log())
};
ConnectyCube.init(CREDENTIALS, CONFIG);
```

2 - send a message from Web. then collect ALL SDK logs at RN side and share here

**Comment by HusseinY-DeV** [comment]
> Ok then let's do the following
> 
> at RN side:
> 
> 1 - enable logs
> 
> ```
> const CONFIG = {
>   debug: { mode: 1 }, // enable DEBUG mode (mode 0 is logs off, mode 1 -> console.log())
> };
> ConnectyCube.init(CREDENTIALS, CONFIG);
> ```
> 
> 2 - send a message from Web. then collect ALL SDK logs at RN side and share here

Yes sir. Danke

**Comment by DaveLomber** [comment]
Closed as too old, please raise a new ticket if this is still actual
